# fly.toml app configuration file generated for trendplus on 2026-01-16T13:40:33+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trendplus'
primary_region = 'fra'

[env]
  ASPNETCORE_URLS = "http://0.0.0.0:8080"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = false
  # allow scaling down to zero when idle (reduces cost to near $0)
  min_machines_running = 0
  # enable machine stopping when idle and automatic start on request
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
