START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419113212_AddAnalyticsCostSnapshotTables') THEN
    CREATE TABLE analytics_cost_snapshot_batches (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        scope character varying(50) NOT NULL DEFAULT 'access_origin',
        status character varying(20) NOT NULL DEFAULT 'draft',
        created_at_utc timestamp with time zone NOT NULL,
        generated_at_utc timestamp with time zone,
        activated_at_utc timestamp with time zone,
        deactivated_at_utc timestamp with time zone,
        created_by character varying(100) NOT NULL DEFAULT 'system',
        description text,
        row_count integer NOT NULL DEFAULT 0,
        total_revenue_covered numeric(18,2) NOT NULL DEFAULT 0.0,
        coverage_pct double precision NOT NULL DEFAULT 0.0,
        no_cost_pct double precision NOT NULL DEFAULT 0.0,
        generation_duration_ms integer,
        dry_run boolean NOT NULL DEFAULT FALSE,
        error_message text,
        metadata_json jsonb,
        CONSTRAINT "PK_analytics_cost_snapshot_batches" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419113212_AddAnalyticsCostSnapshotTables') THEN
    CREATE TABLE analytics_sale_line_cost_snapshots (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        batch_id bigint NOT NULL,
        prodaja_stavka_id integer NOT NULL,
        resolved_unit_cost numeric(18,4) NOT NULL,
        cost_source smallint NOT NULL,
        product_cost_rsd_at_snapshot numeric(18,4),
        product_cost_legacy_at_snapshot numeric(18,4),
        artikal_id integer NOT NULL,
        CONSTRAINT "PK_analytics_sale_line_cost_snapshots" PRIMARY KEY (id),
        CONSTRAINT "FK_analytics_sale_line_cost_snapshots_analytics_cost_snapshot_~" FOREIGN KEY (batch_id) REFERENCES analytics_cost_snapshot_batches (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419113212_AddAnalyticsCostSnapshotTables') THEN
    CREATE INDEX ix_snapshot_batches_status ON analytics_cost_snapshot_batches (status, scope);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419113212_AddAnalyticsCostSnapshotTables') THEN
    CREATE UNIQUE INDEX ux_snapshot_batches_active_scope ON analytics_cost_snapshot_batches (scope) WHERE "status" = 'active';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419113212_AddAnalyticsCostSnapshotTables') THEN
    CREATE INDEX ix_snapshot_lines_batch_source ON analytics_sale_line_cost_snapshots (batch_id, cost_source);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419113212_AddAnalyticsCostSnapshotTables') THEN
    CREATE INDEX ix_snapshot_lines_stavka ON analytics_sale_line_cost_snapshots (prodaja_stavka_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419113212_AddAnalyticsCostSnapshotTables') THEN
    CREATE UNIQUE INDEX ux_snapshot_lines_batch_stavka ON analytics_sale_line_cost_snapshots (batch_id, prodaja_stavka_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419113212_AddAnalyticsCostSnapshotTables') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260419113212_AddAnalyticsCostSnapshotTables', '8.0.22');
    END IF;
END $EF$;
COMMIT;

