using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Infrastructure.DbContexts;

#nullable disable

namespace Infrastructure.Migrations.AnalyticsDb
{
    /// <inheritdoc />
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260225100000_AddAnalyticsDimensionsAndMovements")]
    public partial class AddAnalyticsDimensionsAndMovements : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent on purpose. Before 2026-09-19 this class had no [Migration]
            // attribute, so EF never ran it and DatabaseInitializer's
            // EnsureCoreAnalyticsDimensionTablesAsync self-heal created these columns,
            // tables and indexes instead. Databases bootstrapped that way already have
            // the schema but no history row; a plain AddColumn/CreateTable then fails
            // with 42701/42P07. On a fresh database this SQL creates the same schema
            // the original EF operations did.
            migrationBuilder.Sql("""
                ALTER TABLE "ProductsDim" ADD COLUMN IF NOT EXISTS "PLU" character varying(100);
                ALTER TABLE "ProductsDim" ADD COLUMN IF NOT EXISTS "MinimalnaKolicina" integer;
                ALTER TABLE "StoresDim" ADD COLUMN IF NOT EXISTS "Telefon" character varying(50);
                ALTER TABLE "StoresDim" ADD COLUMN IF NOT EXISTS "Menedzer" character varying(200);
                ALTER TABLE "SalesLineFacts" ADD COLUMN IF NOT EXISTS "NabavnaCena" numeric(18,2);

                CREATE TABLE IF NOT EXISTS "SuppliersDim" (
                    "SupplierKey" integer GENERATED BY DEFAULT AS IDENTITY,
                    "SupplierId" integer NOT NULL,
                    "Naziv" character varying(300) NOT NULL DEFAULT '',
                    "Adresa" character varying(500),
                    "Telefon" character varying(50),
                    "Napomena" character varying(500),
                    "DataOrigin" character varying(32) NOT NULL DEFAULT 'existing',
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_SuppliersDim" PRIMARY KEY ("SupplierKey")
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_SuppliersDim_SupplierId" ON "SuppliersDim" ("SupplierId");

                CREATE TABLE IF NOT EXISTS "SeasonsDim" (
                    "SeasonKey" integer GENERATED BY DEFAULT AS IDENTITY,
                    "SeasonId" integer NOT NULL,
                    "Naziv" character varying(200) NOT NULL DEFAULT '',
                    "DatumOd" timestamp with time zone NOT NULL,
                    "DatumDo" timestamp with time zone NOT NULL,
                    "DataOrigin" character varying(32) NOT NULL DEFAULT 'existing',
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_SeasonsDim" PRIMARY KEY ("SeasonKey")
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_SeasonsDim_SeasonId" ON "SeasonsDim" ("SeasonId");
                CREATE INDEX IF NOT EXISTS "IX_SeasonsDim_DatumOd" ON "SeasonsDim" ("DatumOd");
                CREATE INDEX IF NOT EXISTS "IX_SeasonsDim_DatumDo" ON "SeasonsDim" ("DatumDo");

                CREATE TABLE IF NOT EXISTS "FootwearTypesDim" (
                    "TypeKey" integer GENERATED BY DEFAULT AS IDENTITY,
                    "TypeId" integer NOT NULL,
                    "Naziv" character varying(200) NOT NULL DEFAULT '',
                    "DataOrigin" character varying(32) NOT NULL DEFAULT 'existing',
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_FootwearTypesDim" PRIMARY KEY ("TypeKey")
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_FootwearTypesDim_TypeId" ON "FootwearTypesDim" ("TypeId");

                CREATE TABLE IF NOT EXISTS "InventoryMovementFacts" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                    "SourceId" integer NOT NULL,
                    "TipPromene" character varying(100) NOT NULL,
                    "Datum" timestamp with time zone NOT NULL,
                    "ArtikalId" integer,
                    "Kolicina" integer,
                    "StaraProdajnaCena" numeric(18,2),
                    "NovaProdajnaCena" numeric(18,2),
                    "Iznos" numeric(18,2) NOT NULL,
                    "StoreId" integer,
                    "DobavljacId" integer,
                    "BrojDokumenta" character varying(100),
                    "KorisnikIme" character varying(200),
                    "DataOrigin" character varying(32) NOT NULL DEFAULT 'existing',
                    CONSTRAINT "PK_InventoryMovementFacts" PRIMARY KEY ("Id")
                );
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_InventoryMovementFacts_SourceId" ON "InventoryMovementFacts" ("SourceId");
                CREATE INDEX IF NOT EXISTS "IX_InventoryMovementFacts_Datum" ON "InventoryMovementFacts" ("Datum");
                CREATE INDEX IF NOT EXISTS "IX_InventoryMovementFacts_TipPromene" ON "InventoryMovementFacts" ("TipPromene");
                CREATE INDEX IF NOT EXISTS "IX_InventoryMovementFacts_ArtikalId_Datum" ON "InventoryMovementFacts" ("ArtikalId", "Datum");
                CREATE INDEX IF NOT EXISTS "IX_InventoryMovementFacts_StoreId_Datum" ON "InventoryMovementFacts" ("StoreId", "Datum");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "InventoryMovementFacts");
            migrationBuilder.DropTable(name: "FootwearTypesDim");
            migrationBuilder.DropTable(name: "SeasonsDim");
            migrationBuilder.DropTable(name: "SuppliersDim");

            migrationBuilder.DropColumn(name: "NabavnaCena",        table: "SalesLineFacts");
            migrationBuilder.DropColumn(name: "Telefon",            table: "StoresDim");
            migrationBuilder.DropColumn(name: "Menedzer",           table: "StoresDim");
            migrationBuilder.DropColumn(name: "PLU",                table: "ProductsDim");
            migrationBuilder.DropColumn(name: "MinimalnaKolicina",  table: "ProductsDim");
        }
    }
}
