// <auto-generated />
using System;
using Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations.AnalyticsDb
{
    [DbContext(typeof(AnalyticsDbContext))]
    partial class AnalyticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Model.AmazonShoeProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Asin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Domain")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("LastSynced")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ProductUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<float>("TrendScore")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Asin")
                        .IsUnique();

                    b.HasIndex("Category");

                    b.HasIndex("Gender");

                    b.HasIndex("LastSynced");

                    b.HasIndex("Rating");

                    b.HasIndex("TrendScore");

                    b.ToTable("amazon_shoe_products", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Analytics.AnalyticsActionItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("ConfidencePct")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DataQualityStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("ImpactEstimateRsd")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("RecommendationStatus")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ReliabilityPct")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UpdatedByUserName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Priority")
                        .HasDatabaseName("idx_analytics_action_priority");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_analytics_action_status");

                    b.HasIndex("Priority", "Status")
                        .HasDatabaseName("idx_analytics_action_priority_status");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("idx_analytics_action_updated");

                    b.HasIndex("SourceType", "CreatedAtUtc")
                        .HasDatabaseName("idx_analytics_action_source_created");

                    b.HasIndex("SourceType", "SourceKey")
                        .IsUnique()
                        .HasDatabaseName("idx_analytics_action_sourcekey_open")
                        .HasFilter("\"Status\" IN ('new', 'accepted', 'deferred')");

                    b.HasIndex("SourceType", "SourceKey", "Status")
                        .HasDatabaseName("idx_analytics_action_sourcekey_status");

                    b.HasIndex("Status", "UpdatedAtUtc")
                        .HasDatabaseName("idx_analytics_action_status_updated");

                    b.ToTable("analytics_action_items", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Analytics.EuTrend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Brand");

                    b.HasIndex("Category");

                    b.HasIndex("Rank");

                    b.HasIndex("Season");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("EuTrends", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Analytics.GlobalTrendScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("ColorScore")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("EuTrendScore")
                        .HasColumnType("real");

                    b.Property<float>("FinalGlobalScore")
                        .HasColumnType("real");

                    b.Property<int>("LocalProductId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MatchedEuTrendId")
                        .HasColumnType("uuid");

                    b.Property<string[]>("MatchedHashtags")
                        .HasColumnType("text[]");

                    b.Property<float>("PriceScore")
                        .HasColumnType("real");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Recommendations")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<float>("SeasonScore")
                        .HasColumnType("real");

                    b.Property<float>("SimilarityScore")
                        .HasColumnType("real");

                    b.Property<float>("SocialTrendScore")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EuTrendScore");

                    b.HasIndex("FinalGlobalScore");

                    b.HasIndex("LocalProductId")
                        .IsUnique();

                    b.HasIndex("SocialTrendScore");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("GlobalTrendScores", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Analytics.InventoryRecommendation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("MomentumScore")
                        .HasColumnType("double precision")
                        .HasColumnName("momentum_score");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_id");

                    b.Property<int>("RecommendedQty")
                        .HasColumnType("integer")
                        .HasColumnName("recommended_qty");

                    b.Property<double>("SalesVelocity")
                        .HasColumnType("double precision")
                        .HasColumnName("sales_velocity");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.Property<double>("StockOnHand")
                        .HasColumnType("double precision")
                        .HasColumnName("stock_on_hand");

                    b.Property<double>("TrendScore")
                        .HasColumnType("double precision")
                        .HasColumnName("trend_score");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate")
                        .HasDatabaseName("idx_inv_rec_date");

                    b.HasIndex("ProductId", "SnapshotDate")
                        .HasDatabaseName("idx_inv_rec_product");

                    b.ToTable("inventory_recommendations", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Analytics.SocialTrend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("AverageEngagement")
                        .HasColumnType("real");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hashtag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float?>("InstagramGrowth")
                        .HasColumnType("real");

                    b.Property<float?>("PinterestGrowth")
                        .HasColumnType("real");

                    b.Property<int>("PostsLastMonth")
                        .HasColumnType("integer");

                    b.Property<int>("PostsThisMonth")
                        .HasColumnType("integer");

                    b.Property<float?>("TiktokGrowth")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Hashtag");

                    b.HasIndex("TiktokGrowth");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("Category", "Hashtag")
                        .IsUnique();

                    b.ToTable("SocialTrends", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Analytics.TrendHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("EuTrendScore")
                        .HasColumnType("real");

                    b.Property<float>("FinalGlobalScore")
                        .HasColumnType("real");

                    b.Property<int>("LocalProductId")
                        .HasColumnType("integer");

                    b.Property<float?>("SocialTrendScore")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("LocalProductId");

                    b.HasIndex("LocalProductId", "Date")
                        .IsUnique();

                    b.ToTable("TrendHistory", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Analytics.TrendProductMomentum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CanonicalKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("canonical_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsNewEntry")
                        .HasColumnType("boolean")
                        .HasColumnName("is_new_entry");

                    b.Property<double>("MomentumScore")
                        .HasColumnType("double precision")
                        .HasColumnName("momentum_score");

                    b.Property<int>("RankDelta")
                        .HasColumnType("integer")
                        .HasColumnName("rank_delta");

                    b.Property<double>("ScoreDelta")
                        .HasColumnType("double precision")
                        .HasColumnName("score_delta");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate", "CanonicalKey")
                        .HasDatabaseName("idx_trend_momentum_date_key");

                    b.ToTable("trend_product_momentum", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Analytics.TrendProductSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brand");

                    b.Property<string>("CanonicalKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("canonical_key");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Market")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("market");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("product_name");

                    b.Property<int>("RankGlobal")
                        .HasColumnType("integer")
                        .HasColumnName("rank_global");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.Property<double?>("SocialScore")
                        .HasColumnType("double precision")
                        .HasColumnName("social_score");

                    b.Property<int>("SourceCount")
                        .HasColumnType("integer")
                        .HasColumnName("source_count");

                    b.Property<int>("UniqueSources")
                        .HasColumnType("integer")
                        .HasColumnName("unique_sources");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalKey", "SnapshotDate")
                        .HasDatabaseName("idx_trend_snapshots_key_date");

                    b.ToTable("trend_product_snapshots", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Analytics.TrendplusIndexRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("BaseComponent")
                        .HasColumnType("double precision")
                        .HasColumnName("base_component");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("IndexValue")
                        .HasColumnType("double precision")
                        .HasColumnName("index_value");

                    b.Property<double>("MomentumComponent")
                        .HasColumnType("double precision")
                        .HasColumnName("momentum_component");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("scope_type");

                    b.Property<string>("ScopeValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scope_value");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date")
                        .HasColumnName("snapshot_date");

                    b.Property<double>("SocialComponent")
                        .HasColumnType("double precision")
                        .HasColumnName("social_component");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotDate")
                        .HasDatabaseName("idx_trendplus_index_date");

                    b.HasIndex("ScopeType", "ScopeValue", "SnapshotDate")
                        .IsUnique()
                        .HasDatabaseName("idx_trendplus_index_scope_date");

                    b.ToTable("trendplus_index", (string)null);
                });

            modelBuilder.Entity("Domain.Model.EbayShoeProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("EbayItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSynced")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Marketplace")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("text");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<float>("TrendScore")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("EbayItemId")
                        .IsUnique();

                    b.HasIndex("Gender");

                    b.HasIndex("LastSynced");

                    b.HasIndex("Rating");

                    b.HasIndex("TrendScore");

                    b.ToTable("ebay_shoe_products", (string)null);
                });

            modelBuilder.Entity("Domain.Model.FootwearTypesDim", b =>
                {
                    b.Property<int>("TypeKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeKey"));

                    b.Property<string>("DataOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("existing");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TypeKey");

                    b.HasIndex("TypeId")
                        .IsUnique();

                    b.ToTable("FootwearTypesDim");
                });

            modelBuilder.Entity("Domain.Model.GoogleShoppingProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Domain")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("LastSynced")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ProductId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<float>("TrendScore")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Gender");

                    b.HasIndex("LastSynced");

                    b.HasIndex("Position");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasFilter("\"ProductId\" IS NOT NULL");

                    b.HasIndex("TrendScore");

                    b.ToTable("google_shopping_products", (string)null);
                });

            modelBuilder.Entity("Domain.Model.InventoryMovementFact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ArtikalId")
                        .HasColumnType("integer");

                    b.Property<string>("BrojDokumenta")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DataOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("existing");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DobavljacId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("Kolicina")
                        .HasColumnType("integer");

                    b.Property<string>("KorisnikIme")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("NovaProdajnaCena")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StaraProdajnaCena")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("StoreId")
                        .HasColumnType("integer");

                    b.Property<string>("TipPromene")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Datum");

                    b.HasIndex("TipPromene");

                    b.HasIndex("ArtikalId", "Datum");

                    b.HasIndex("SourceId", "DataOrigin")
                        .IsUnique();

                    b.HasIndex("StoreId", "Datum");

                    b.ToTable("InventoryMovementFacts", (string)null);
                });

            modelBuilder.Entity("Domain.Model.PerformanceLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ExceptionMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("RequestData")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("RequestName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ResponseData")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DurationMs");

                    b.HasIndex("RequestName");

                    b.HasIndex("Timestamp");

                    b.ToTable("PerformanceLogs", (string)null);
                });

            modelBuilder.Entity("Domain.Model.ProductsDim", b =>
                {
                    b.Property<int>("ProductKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductKey"));

                    b.Property<string>("Boja")
                        .HasColumnType("text");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("existing");

                    b.Property<decimal?>("FirstSalePrice")
                        .HasColumnType("numeric");

                    b.Property<int?>("FootwearTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("Kolicina")
                        .HasColumnType("integer");

                    b.Property<string>("Materijal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("MinimalnaKolicina")
                        .HasColumnType("integer");

                    b.Property<string>("PLU")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PurchasePriceRsd")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("numeric");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Velicina")
                        .HasColumnType("text");

                    b.HasKey("ProductKey");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("Timestamp");

                    b.ToTable("ProductsDim");
                });

            modelBuilder.Entity("Domain.Model.ReturnFact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BrojZapisnika")
                        .HasColumnType("text");

                    b.Property<string>("DataOrigin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeaderReason")
                        .HasColumnType("text");

                    b.Property<string>("ItemCondition")
                        .HasColumnType("text");

                    b.Property<decimal>("LineAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("LineReason")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<int>("ReturnId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReturnTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SourceLineId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ReturnFacts");
                });

            modelBuilder.Entity("Domain.Model.SalesFact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BrojRacuna")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DataOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("existing");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SaleTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TotalLines")
                        .HasColumnType("integer");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SaleId")
                        .IsUnique();

                    b.HasIndex("SaleTimestampUtc");

                    b.HasIndex("StoreId");

                    b.ToTable("SalesFacts", (string)null);
                });

            modelBuilder.Entity("Domain.Model.SalesLineFact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DataOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("existing");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("NabavnaCena")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<int>("SaleId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SaleId");

                    b.HasIndex("ProductId", "SaleId");

                    b.ToTable("SalesLineFacts", (string)null);
                });

            modelBuilder.Entity("Domain.Model.SeasonsDim", b =>
                {
                    b.Property<int>("SeasonKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeasonKey"));

                    b.Property<string>("DataOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("existing");

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SeasonKey");

                    b.HasIndex("DatumDo");

                    b.HasIndex("DatumOd");

                    b.HasIndex("SeasonId")
                        .IsUnique();

                    b.ToTable("SeasonsDim");
                });

            modelBuilder.Entity("Domain.Model.StoresDim", b =>
                {
                    b.Property<int>("StoreKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoreKey"));

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DataOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("existing");

                    b.Property<string>("Menedzer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StoreId")
                        .HasColumnType("integer");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("StoreKey");

                    b.HasIndex("DataOrigin");

                    b.HasIndex("StoreId")
                        .IsUnique();

                    b.ToTable("StoresDim");
                });

            modelBuilder.Entity("Domain.Model.SuppliersDim", b =>
                {
                    b.Property<int>("SupplierKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupplierKey"));

                    b.Property<string>("Adresa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DataOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("existing");

                    b.Property<string>("Napomena")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SupplierKey");

                    b.HasIndex("SupplierId")
                        .IsUnique();

                    b.ToTable("SuppliersDim");
                });
#pragma warning restore 612, 618
        }
    }
}
