// <auto-generated />
using System;
using Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations.AnalyticsDb
{
    [DbContext(typeof(AnalyticsDbContext))]
    partial class AnalyticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Model.FootwearTypesDim", b =>
                {
                    b.Property<int>("TypeKey").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeKey"));
                    b.Property<string>("DataOrigin").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasDefaultValue("existing");
                    b.Property<string>("Naziv").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<int>("TypeId").HasColumnType("integer");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("TypeKey");
                    b.HasIndex("TypeId").IsUnique();
                    b.ToTable("FootwearTypesDim");
                });

            modelBuilder.Entity("Domain.Model.InventoryMovementFact", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    b.Property<int?>("ArtikalId").HasColumnType("integer");
                    b.Property<string>("BrojDokumenta").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("DataOrigin").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasDefaultValue("existing");
                    b.Property<DateTime>("Datum").HasColumnType("timestamp with time zone");
                    b.Property<int?>("DobavljacId").HasColumnType("integer");
                    b.Property<decimal>("Iznos").HasColumnType("numeric(18,2)");
                    b.Property<int?>("Kolicina").HasColumnType("integer");
                    b.Property<string>("KorisnikIme").HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<decimal?>("NovaProdajnaCena").HasColumnType("numeric(18,2)");
                    b.Property<int>("SourceId").HasColumnType("integer");
                    b.Property<decimal?>("StaraProdajnaCena").HasColumnType("numeric(18,2)");
                    b.Property<int?>("StoreId").HasColumnType("integer");
                    b.Property<string>("TipPromene").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.HasKey("Id");
                    b.HasIndex("SourceId").IsUnique();
                    b.HasIndex("Datum");
                    b.HasIndex("TipPromene");
                    b.HasIndex("ArtikalId", "Datum");
                    b.HasIndex("StoreId", "Datum");
                    b.ToTable("InventoryMovementFacts");
                });

            modelBuilder.Entity("Domain.Model.PerformanceLog", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    b.Property<long>("DurationMs").HasColumnType("bigint");
                    b.Property<string>("ExceptionMessage").HasMaxLength(2000).HasColumnType("character varying(2000)");
                    b.Property<bool>("IsSuccess").HasColumnType("boolean");
                    b.Property<string>("RequestData").HasMaxLength(4000).HasColumnType("character varying(4000)");
                    b.Property<string>("RequestName").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<string>("RequestType").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("ResponseData").HasMaxLength(4000).HasColumnType("character varying(4000)");
                    b.Property<DateTime>("Timestamp").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("DurationMs");
                    b.HasIndex("RequestName");
                    b.HasIndex("Timestamp");
                    b.ToTable("PerformanceLogs", (string)null);
                });

            modelBuilder.Entity("Domain.Model.ProductsDim", b =>
                {
                    b.Property<int>("ProductKey").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductKey"));
                    b.Property<string>("Boja").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("Brand").IsRequired().HasColumnType("text");
                    b.Property<string>("Category").IsRequired().HasColumnType("text");
                    b.Property<string>("DataOrigin").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasDefaultValue("existing");
                    b.Property<decimal?>("FirstSalePrice").HasColumnType("numeric");
                    b.Property<int?>("FootwearTypeId").HasColumnType("integer");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<int?>("Kolicina").HasColumnType("integer");
                    b.Property<string>("Materijal").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<int?>("MinimalnaKolicina").HasColumnType("integer");
                    b.Property<string>("PLU").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<int>("ProductId").HasColumnType("integer");
                    b.Property<string>("ProductName").IsRequired().HasColumnType("text");
                    b.Property<decimal?>("PurchasePrice").HasColumnType("numeric");
                    b.Property<decimal?>("PurchasePriceRsd").HasColumnType("numeric");
                    b.Property<decimal?>("SalePrice").HasColumnType("numeric");
                    b.Property<int?>("SeasonId").HasColumnType("integer");
                    b.Property<string>("SubCategory").IsRequired().HasColumnType("text");
                    b.Property<int?>("SupplierId").HasColumnType("integer");
                    b.Property<DateTime>("Timestamp").HasColumnType("timestamp with time zone");
                    b.Property<string>("Velicina").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.HasKey("ProductKey");
                    b.HasIndex("ProductId");
                    b.HasIndex("Timestamp");
                    b.ToTable("ProductsDim");
                });

            modelBuilder.Entity("Domain.Model.SalesFact", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    b.Property<string>("BrojRacuna").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<string>("DataOrigin").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasDefaultValue("existing");
                    b.Property<string>("PaymentType").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<int>("SaleId").HasColumnType("integer");
                    b.Property<DateTime>("SaleTimestampUtc").HasColumnType("timestamp with time zone");
                    b.Property<int>("StoreId").HasColumnType("integer");
                    b.Property<decimal>("TotalAmount").HasColumnType("numeric(18,2)");
                    b.Property<int>("TotalLines").HasColumnType("integer");
                    b.Property<int>("TotalUnits").HasColumnType("integer");
                    b.HasKey("Id");
                    b.HasIndex("SaleId").IsUnique();
                    b.HasIndex("SaleTimestampUtc");
                    b.HasIndex("StoreId");
                    b.ToTable("SalesFacts", (string)null);
                });

            modelBuilder.Entity("Domain.Model.SalesLineFact", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    b.Property<string>("DataOrigin").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasDefaultValue("existing");
                    b.Property<decimal>("LineTotal").HasColumnType("numeric(18,2)");
                    b.Property<decimal?>("NabavnaCena").HasColumnType("numeric(18,2)");
                    b.Property<int>("ProductId").HasColumnType("integer");
                    b.Property<int>("Qty").HasColumnType("integer");
                    b.Property<int>("SaleId").HasColumnType("integer");
                    b.Property<decimal>("UnitPrice").HasColumnType("numeric(18,2)");
                    b.HasKey("Id");
                    b.HasIndex("SaleId");
                    b.HasIndex("ProductId", "SaleId");
                    b.ToTable("SalesLineFacts", (string)null);
                });

            modelBuilder.Entity("Domain.Model.SeasonsDim", b =>
                {
                    b.Property<int>("SeasonKey").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeasonKey"));
                    b.Property<string>("DataOrigin").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasDefaultValue("existing");
                    b.Property<DateTime>("DatumDo").HasColumnType("timestamp with time zone");
                    b.Property<DateTime>("DatumOd").HasColumnType("timestamp with time zone");
                    b.Property<string>("Naziv").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<int>("SeasonId").HasColumnType("integer");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("SeasonKey");
                    b.HasIndex("SeasonId").IsUnique();
                    b.HasIndex("DatumOd");
                    b.HasIndex("DatumDo");
                    b.ToTable("SeasonsDim");
                });

            modelBuilder.Entity("Domain.Model.StoresDim", b =>
                {
                    b.Property<int>("StoreKey").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoreKey"));
                    b.Property<string>("City").HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("Menedzer").HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("Region").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<int>("StoreId").HasColumnType("integer");
                    b.Property<string>("StoreName").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                    b.Property<string>("Telefon").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.HasKey("StoreKey");
                    b.HasIndex("StoreId").IsUnique();
                    b.ToTable("StoresDim");
                });

            modelBuilder.Entity("Domain.Model.SuppliersDim", b =>
                {
                    b.Property<int>("SupplierKey").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SupplierKey"));
                    b.Property<string>("Adresa").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<string>("DataOrigin").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)").HasDefaultValue("existing");
                    b.Property<string>("Napomena").HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<string>("Naziv").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)");
                    b.Property<int>("SupplierId").HasColumnType("integer");
                    b.Property<string>("Telefon").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("SupplierKey");
                    b.HasIndex("SupplierId").IsUnique();
                    b.ToTable("SuppliersDim");
                });

#pragma warning restore 612, 618
        }
    }
}
