using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

using Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TrendplusDbContext))]
    [Migration("20260318120000_AddDocumentExportSystem")]
    public partial class AddDocumentExportSystem : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "DocumentAudits" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                    "DocumentId" uuid NOT NULL,
                    "Action" character varying(64) NOT NULL,
                    "UserId" character varying(200) NOT NULL,
                    "UserName" character varying(200) NOT NULL,
                    "Roles" character varying(1000),
                    "IpAddress" character varying(128),
                    "UserAgent" character varying(1024),
                    "DetailsJson" text,
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_DocumentAudits" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "DocumentTemplates" (
                    "Id" uuid NOT NULL,
                    "Name" character varying(200) NOT NULL,
                    "Version" integer NOT NULL,
                    "Type" character varying(100) NOT NULL,
                    "Locale" character varying(16) NOT NULL,
                    "Content" text NOT NULL,
                    "HeaderContent" text,
                    "FooterContent" text,
                    "IsActive" boolean NOT NULL,
                    "CreatedByUserId" character varying(200),
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_DocumentTemplates" PRIMARY KEY ("Id")
                );

                CREATE TABLE IF NOT EXISTS "Documents" (
                    "Id" uuid NOT NULL,
                    "BatchId" uuid,
                    "TemplateId" uuid,
                    "TemplateVersion" integer NOT NULL,
                    "TemplateName" character varying(200) NOT NULL,
                    "DocumentType" character varying(100) NOT NULL,
                    "TableKey" character varying(200) NOT NULL,
                    "TableTitle" character varying(300) NOT NULL,
                    "Format" character varying(32) NOT NULL,
                    "Orientation" character varying(32) NOT NULL,
                    "Status" character varying(32) NOT NULL,
                    "RequestedByUserId" character varying(200) NOT NULL,
                    "RequestedByUserName" character varying(200) NOT NULL,
                    "RequestedByRoles" character varying(1000),
                    "Locale" character varying(16),
                    "IncludeFiltersAndMetadata" boolean NOT NULL,
                    "IsPreview" boolean NOT NULL,
                    "IsAsync" boolean NOT NULL,
                    "RowCount" integer NOT NULL,
                    "FiltersJson" text,
                    "MetadataJson" text,
                    "RequestJson" text NOT NULL,
                    "MimeType" character varying(150),
                    "FileName" character varying(260),
                    "StoragePath" character varying(500),
                    "FileUrl" character varying(1000),
                    "SizeBytes" bigint,
                    "Sha256" character varying(128),
                    "ErrorMessage" character varying(4000),
                    "RetryCount" integer NOT NULL,
                    "CreatedAtUtc" timestamp with time zone NOT NULL,
                    "UpdatedAtUtc" timestamp with time zone NOT NULL,
                    "StartedAtUtc" timestamp with time zone,
                    "CompletedAtUtc" timestamp with time zone,
                    "NextAttemptAtUtc" timestamp with time zone,
                    "ExpiresAtUtc" timestamp with time zone,
                    CONSTRAINT "PK_Documents" PRIMARY KEY ("Id")
                );

                CREATE INDEX IF NOT EXISTS "IX_DocumentAudits_DocumentId_CreatedAtUtc"
                    ON "DocumentAudits" ("DocumentId", "CreatedAtUtc");
                CREATE INDEX IF NOT EXISTS "IX_Documents_BatchId"
                    ON "Documents" ("BatchId");
                CREATE INDEX IF NOT EXISTS "IX_Documents_CreatedAtUtc"
                    ON "Documents" ("CreatedAtUtc");
                CREATE INDEX IF NOT EXISTS "IX_Documents_RequestedByUserId"
                    ON "Documents" ("RequestedByUserId");
                CREATE INDEX IF NOT EXISTS "IX_Documents_Status"
                    ON "Documents" ("Status");
                CREATE INDEX IF NOT EXISTS "IX_Documents_Status_NextAttemptAtUtc"
                    ON "Documents" ("Status", "NextAttemptAtUtc");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_DocumentTemplates_Name_Version"
                    ON "DocumentTemplates" ("Name", "Version");
                CREATE INDEX IF NOT EXISTS "IX_DocumentTemplates_Type_IsActive"
                    ON "DocumentTemplates" ("Type", "IsActive");

                INSERT INTO "DocumentTemplates" (
                    "Id", "Name", "Version", "Type", "Locale", "Content", "HeaderContent", "FooterContent", "IsActive", "CreatedByUserId", "CreatedAtUtc"
                )
                VALUES
                (
                    '65f367aa-4206-4b7e-b7d2-7d8ef7351111'::uuid,
                    'analytics-table-default',
                    1,
                    'analytics-table-report',
                    'sr-RS',
                    '<!DOCTYPE html><html><head><meta charset="utf-8" /><title>{{title}}</title><style>{{styles}}</style></head><body class="doc {{orientation}}"><div class="sheet"><header>{{header}}</header><section class="meta"><div><strong>Izvestaj:</strong> {{title}}</div><div><strong>Generisano:</strong> {{generated_at}}</div><div><strong>Korisnik:</strong> {{requested_by}}</div></section><section class="filters"><h3>Filteri</h3>{{filters}}</section><section class="metadata"><h3>Metapodaci</h3>{{metadata}}</section><section class="table-section">{{table}}</section><footer>{{footer}}</footer></div></body></html>',
                    '<div class="doc-header"><h1>{{title}}</h1><p>Trendplus Analytics Export</p></div>',
                    '<div class="doc-footer"><span>Template v{{template_version}}</span><span>{{table_key}}</span></div>',
                    TRUE,
                    'system',
                    TIMESTAMPTZ '2026-03-18 00:00:00+00'
                ),
                (
                    '65f367aa-4206-4b7e-b7d2-7d8ef7352222'::uuid,
                    'executive-summary-default',
                    1,
                    'executive-summary',
                    'sr-RS',
                    '<!DOCTYPE html><html><head><meta charset="utf-8" /><title>{{title}}</title><style>{{styles}}</style></head><body class="doc portrait"><div class="sheet"><header>{{header}}</header><section class="table-section">{{table}}</section><footer>{{footer}}</footer></div></body></html>',
                    '<div class="doc-header"><h1>{{title}}</h1></div>',
                    '<div class="doc-footer">Trendplus Executive Summary</div>',
                    TRUE,
                    'system',
                    TIMESTAMPTZ '2026-03-18 00:00:00+00'
                ),
                (
                    '65f367aa-4206-4b7e-b7d2-7d8ef7353333'::uuid,
                    'receipt-default',
                    1,
                    'receipt',
                    'sr-RS',
                    '<!DOCTYPE html><html><head><meta charset="utf-8" /><title>{{title}}</title><style>{{styles}}</style></head><body class="doc portrait thermal"><div class="sheet">{{table}}</div></body></html>',
                    NULL,
                    NULL,
                    TRUE,
                    'system',
                    TIMESTAMPTZ '2026-03-18 00:00:00+00'
                ),
                (
                    '65f367aa-4206-4b7e-b7d2-7d8ef7354444'::uuid,
                    'label-default',
                    1,
                    'label',
                    'sr-RS',
                    '<!DOCTYPE html><html><head><meta charset="utf-8" /><title>{{title}}</title><style>{{styles}}</style></head><body class="doc portrait label"><div class="sheet">{{table}}</div></body></html>',
                    NULL,
                    NULL,
                    TRUE,
                    'system',
                    TIMESTAMPTZ '2026-03-18 00:00:00+00'
                )
                ON CONFLICT ("Id") DO NOTHING;
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "DocumentAudits";""");
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "Documents";""");
            migrationBuilder.Sql("""DROP TABLE IF EXISTS "DocumentTemplates";""");
        }
    }
}
