// <auto-generated />
using System;
using Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TrendplusDbContext))]
    [Migration("20260507132430_AddWorkerRuntimeSettings")]
    partial class AddWorkerRuntimeSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Model.AccessImportCursor", b =>
                {
                    b.Property<string>("TableKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long?>("CursorId")
                        .HasColumnType("bigint");

                    b.Property<string>("CursorIdColumn")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CursorMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("CursorTieBreakerId")
                        .HasColumnType("bigint");

                    b.Property<string>("CursorTimestampColumn")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("CursorTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("LastLagSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("LastRowsMerged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("LastRowsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LastRunCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastRunStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSuccessfulBatchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LeaseAcquiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OverlapSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60);

                    b.Property<string>("SourceKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("TableKey");

                    b.HasIndex("LastSuccessfulBatchId");

                    b.HasIndex("LeaseExpiresAtUtc");

                    b.ToTable("AccessImportCursors", (string)null);
                });

            modelBuilder.Entity("Domain.Model.AccessImportLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("RowIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("info");

                    b.Property<string>("SourceRowJson")
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("Severity");

                    b.HasIndex("BatchId", "TableName");

                    b.ToTable("AccessImportLog", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Analytics.AnalyticsCostSnapshotBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at_utc");

                    b.Property<double>("CoveragePct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("coverage_pct");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("system")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeactivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("DryRun")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("dry_run");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at_utc");

                    b.Property<int?>("GenerationDurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("generation_duration_ms");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<double>("NoCostPct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("no_cost_pct");

                    b.Property<int>("RowCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("row_count");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("access_origin")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalRevenueCovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_revenue_covered");

                    b.HasKey("Id");

                    b.HasIndex("Scope")
                        .IsUnique()
                        .HasDatabaseName("ux_snapshot_batches_active_scope")
                        .HasFilter("\"status\" = 'active'");

                    b.HasIndex("Status", "Scope")
                        .HasDatabaseName("ix_snapshot_batches_status");

                    b.ToTable("analytics_cost_snapshot_batches", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Analytics.AnalyticsSaleLineCostSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ArtikalId")
                        .HasColumnType("integer")
                        .HasColumnName("artikal_id");

                    b.Property<long>("BatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("batch_id");

                    b.Property<short>("CostSource")
                        .HasColumnType("smallint")
                        .HasColumnName("cost_source");

                    b.Property<int>("ProdajaStavkaId")
                        .HasColumnType("integer")
                        .HasColumnName("prodaja_stavka_id");

                    b.Property<decimal?>("ProductCostLegacyAtSnapshot")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("product_cost_legacy_at_snapshot");

                    b.Property<decimal?>("ProductCostRsdAtSnapshot")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("product_cost_rsd_at_snapshot");

                    b.Property<decimal>("ResolvedUnitCost")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("resolved_unit_cost");

                    b.HasKey("Id");

                    b.HasIndex("ProdajaStavkaId")
                        .HasDatabaseName("ix_snapshot_lines_stavka");

                    b.HasIndex("BatchId", "CostSource")
                        .HasDatabaseName("ix_snapshot_lines_batch_source");

                    b.HasIndex("BatchId", "ProdajaStavkaId")
                        .IsUnique()
                        .HasDatabaseName("ux_snapshot_lines_batch_stavka");

                    b.ToTable("analytics_sale_line_cost_snapshots", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Artikli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Boja")
                        .HasColumnType("text");

                    b.Property<string>("DataOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("existing");

                    b.Property<int?>("IDDobavljac")
                        .HasColumnType("integer");

                    b.Property<int?>("IDObjekat")
                        .HasColumnType("integer");

                    b.Property<int?>("IDSezona")
                        .HasColumnType("integer");

                    b.Property<int?>("IDTipObuce")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Kategorija")
                        .HasColumnType("text");

                    b.Property<int?>("Kolicina")
                        .HasColumnType("integer");

                    b.Property<string>("Komentar")
                        .HasColumnType("text");

                    b.Property<string>("Materijal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("MinimalnaKolicina")
                        .HasColumnType("integer");

                    b.Property<decimal?>("NabavnaCena")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NabavnaCenaDin")
                        .HasColumnType("numeric");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PLU")
                        .HasColumnType("text");

                    b.Property<string>("Pol")
                        .HasColumnType("text");

                    b.Property<decimal?>("ProdajnaCena")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrvaProdajnaCena")
                        .HasColumnType("numeric");

                    b.Property<long?>("SourceBatchId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long?>("SourceRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceTableKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Velicina")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataOrigin");

                    b.HasIndex("IDDobavljac");

                    b.HasIndex("IDObjekat");

                    b.HasIndex("ImagePath");

                    b.HasIndex("IDObjekat", "IDDobavljac");

                    b.HasIndex("DataOrigin", "SourceTableKey", "SourceRowId")
                        .IsUnique()
                        .HasFilter("\"DataOrigin\" = 'access' AND \"SourceTableKey\" IS NOT NULL AND \"SourceRowId\" IS NOT NULL");

                    b.HasIndex("DataOrigin", "SourceTableKey", "SourceUpdatedAtUtc", "SourceRowId");

                    b.ToTable("Artikli", (string)null);
                });

            modelBuilder.Entity("Domain.Model.CreatedIdDto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.ToTable("CreatedIds");
                });

            modelBuilder.Entity("Domain.Model.CrossPlatformProductAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeichmannUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceDeichmann")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceZalando")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ZalandoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CrossPlatformProducts");
                });

            modelBuilder.Entity("Domain.Model.DataImportBatch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("CancellationRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("CancellationRequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStep")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CurrentTable")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CursorAfterJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CursorBeforeJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CursorSnapshot")
                        .HasColumnType("jsonb");

                    b.Property<string>("DataOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("access");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorDetailsJson")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ImportMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("auto");

                    b.Property<string>("ImportStrategy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("full");

                    b.Property<bool>("IncludeAnalytics")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IncludeTemporaryTables")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsIncremental")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OverwriteExisting")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ProcessedRowCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ProgressPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("RowsAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("RowsInserted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("RowsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("RowsRejected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("RowsSkippedStale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("RowsStaged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("RowsUnchanged")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("RowsUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("RowsWritten")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ShadowMismatchCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("SkipInvalidForeignKeys")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("SkippedRowCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("SourceFileHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SourceFilePath")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("SourceStorageKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("SourceStorageProvider")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SummaryJson")
                        .HasColumnType("text");

                    b.Property<int>("TotalErrors")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalImported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CancellationRequested");

                    b.HasIndex("LastHeartbeatUtc");

                    b.HasIndex("QueuedAtUtc");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("DataImportBatches", (string)null);
                });

            modelBuilder.Entity("Domain.Model.DnevnikPromena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArtikalId")
                        .HasColumnType("integer");

                    b.Property<string>("BrojRacuna")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DataOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("existing");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DobavljacId")
                        .HasColumnType("integer");

                    b.Property<int?>("IDObjekat")
                        .HasColumnType("integer");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Kolicina")
                        .HasColumnType("integer");

                    b.Property<string>("Komentar")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("KorisnikIme")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("NovaProdajnaCena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RedniBroj")
                        .HasColumnType("integer");

                    b.Property<long?>("SourceBatchId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long?>("SourceRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceTableKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("StaraProdajnaCena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipPromene")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DataOrigin");

                    b.HasIndex("IDObjekat", "Datum");

                    b.HasIndex("DataOrigin", "SourceTableKey", "SourceRowId")
                        .HasFilter("\"DataOrigin\" = 'access' AND \"SourceTableKey\" IS NOT NULL AND \"SourceRowId\" IS NOT NULL");

                    b.HasIndex("DataOrigin", "SourceTableKey", "SourceUpdatedAtUtc", "SourceRowId");

                    b.ToTable("DnevnikPromena", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Dobavljac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .HasColumnType("text");

                    b.Property<string>("DataOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("existing");

                    b.Property<string>("Napomena")
                        .HasColumnType("text");

                    b.Property<string>("Naziv")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dobavljaci", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Documents.DocumentAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "CreatedAtUtc");

                    b.ToTable("DocumentAudits", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Documents.DocumentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FiltersJson")
                        .HasColumnType("text");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IncludeFiltersAndMetadata")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAsync")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPreview")
                        .HasColumnType("boolean");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestedByRoles")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RequestedByUserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer");

                    b.Property<string>("Sha256")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TableKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TableTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TemplateVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "NextAttemptAtUtc");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Documents.DocumentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FooterContent")
                        .HasColumnType("text");

                    b.Property<string>("HeaderContent")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Version")
                        .IsUnique();

                    b.HasIndex("Type", "IsActive");

                    b.ToTable("DocumentTemplates", (string)null);
                });

            modelBuilder.Entity("Domain.Model.ErrorRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientApp")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Path")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ErrorRecords", (string)null);
                });

            modelBuilder.Entity("Domain.Model.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsProcessed");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Povracaj.PovracajStavka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cena");

                    b.Property<int>("IdArtikal")
                        .HasColumnType("integer")
                        .HasColumnName("id_artikal");

                    b.Property<int>("IdPovracaj")
                        .HasColumnType("integer")
                        .HasColumnName("id_povracaj");

                    b.Property<int>("Kolicina")
                        .HasColumnType("integer")
                        .HasColumnName("kolicina");

                    b.Property<string>("Razlog")
                        .HasColumnType("text")
                        .HasColumnName("razlog");

                    b.Property<long?>("SourceBatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_batch_id");

                    b.Property<string>("SourceHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_hash");

                    b.Property<long?>("SourceRowId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_row_id");

                    b.Property<string>("SourceTableKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_table_key");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at_utc");

                    b.Property<string>("StanjeArtikla")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stanje_artikla");

                    b.HasKey("Id");

                    b.HasIndex("IdArtikal");

                    b.HasIndex("IdPovracaj");

                    b.HasIndex("SourceTableKey", "SourceRowId")
                        .IsUnique()
                        .HasFilter("source_table_key IS NOT NULL AND source_row_id IS NOT NULL");

                    b.HasIndex("SourceTableKey", "SourceUpdatedAtUtc", "SourceRowId");

                    b.ToTable("povracaj_stavke", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Povracaj.PovracajZaglavlje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojZapisnika")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("broj_zapisnika");

                    b.Property<string>("DataOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("existing")
                        .HasColumnName("data_origin");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datum_kreiranja");

                    b.Property<DateTime?>("DatumOdobrenja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datum_odobrenja");

                    b.Property<DateTime>("DatumPovracaja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datum_povracaja");

                    b.Property<int>("IDDobavljac")
                        .HasColumnType("integer")
                        .HasColumnName("id_dobavljac");

                    b.Property<string>("Komentar")
                        .HasColumnType("text")
                        .HasColumnName("komentar");

                    b.Property<string>("KreatorKorisnik")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("kreirao_korisnik");

                    b.Property<string>("OdobrioKorisnik")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("odobrio_korisnik");

                    b.Property<string>("RazlogPovracaja")
                        .HasColumnType("text")
                        .HasColumnName("razlog_povracaja");

                    b.Property<long?>("SourceBatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_batch_id");

                    b.Property<string>("SourceHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_hash");

                    b.Property<long?>("SourceRowId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_row_id");

                    b.Property<string>("SourceTableKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_table_key");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("UkupanIznos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ukupan_iznos");

                    b.HasKey("Id");

                    b.HasIndex("BrojZapisnika")
                        .IsUnique();

                    b.HasIndex("DatumPovracaja");

                    b.HasIndex("IDDobavljac");

                    b.HasIndex("DataOrigin", "SourceTableKey", "SourceRowId")
                        .IsUnique()
                        .HasFilter("data_origin = 'access' AND source_table_key IS NOT NULL AND source_row_id IS NOT NULL");

                    b.HasIndex("DataOrigin", "SourceTableKey", "SourceUpdatedAtUtc", "SourceRowId");

                    b.ToTable("povracaj_zaglavlje", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Prodaja.ProdajaStavka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cena");

                    b.Property<int>("IdArtikal")
                        .HasColumnType("integer")
                        .HasColumnName("id_artikal");

                    b.Property<int>("IdProdaja")
                        .HasColumnType("integer")
                        .HasColumnName("id_prodaja");

                    b.Property<int>("Kolicina")
                        .HasColumnType("integer")
                        .HasColumnName("kolicina");

                    b.Property<decimal?>("NabavnaCena")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("nabavna_cena");

                    b.Property<long?>("SourceBatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_batch_id");

                    b.Property<string>("SourceHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_hash");

                    b.Property<long?>("SourceRowId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_row_id");

                    b.Property<string>("SourceTableKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_table_key");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("IdArtikal");

                    b.HasIndex("IdProdaja", "IdArtikal");

                    b.HasIndex("SourceTableKey", "SourceRowId")
                        .IsUnique()
                        .HasFilter("source_table_key IS NOT NULL AND source_row_id IS NOT NULL");

                    b.HasIndex("SourceTableKey", "SourceUpdatedAtUtc", "SourceRowId");

                    b.ToTable("prodaja_stavke", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Prodaja.ProdajaZaglavlje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojRacuna")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("broj_racuna");

                    b.Property<string>("DataOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("existing")
                        .HasColumnName("data_origin");

                    b.Property<DateTime>("DatumProdaje")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datum_prodaje");

                    b.Property<int?>("IDObjekat")
                        .HasColumnType("integer")
                        .HasColumnName("id_objekat");

                    b.Property<string>("KorisnikIme")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("korisnik_ime");

                    b.Property<string>("NacinPlacanja")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nacin_placanja");

                    b.Property<long?>("SourceBatchId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_batch_id");

                    b.Property<string>("SourceHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_hash");

                    b.Property<long?>("SourceRowId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_row_id");

                    b.Property<string>("SourceTableKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_table_key");

                    b.Property<DateTime?>("SourceUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("DataOrigin", "DatumProdaje");

                    b.HasIndex("DatumProdaje", "IDObjekat");

                    b.HasIndex("DataOrigin", "SourceTableKey", "SourceRowId")
                        .IsUnique()
                        .HasFilter("data_origin = 'access' AND source_table_key IS NOT NULL AND source_row_id IS NOT NULL");

                    b.HasIndex("DataOrigin", "SourceTableKey", "SourceUpdatedAtUtc", "SourceRowId");

                    b.ToTable("prodaja_zaglavlje", (string)null);
                });

            modelBuilder.Entity("Domain.Model.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId", "IsPrimary")
                        .HasFilter("\"IsPrimary\" = true");

                    b.ToTable("ProductImages", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Sezona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DataOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("existing");

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Sezone", (string)null);
                });

            modelBuilder.Entity("Domain.Model.TipObuce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DataOrigin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("existing");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoviObuce", (string)null);
                });

            modelBuilder.Entity("Domain.Model.WorkerRuntimeSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsManuallyStopped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsScheduleEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc");

                    b.HasIndex("WorkerName")
                        .IsUnique();

                    b.ToTable("WorkerRuntimeSettings", (string)null);
                });

            modelBuilder.Entity("Domain.Transfers.Transfer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("DestinationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("Reserve")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("SourceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("draft");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("SourceId", "DestinationId");

                    b.ToTable("Transfers", (string)null);
                });

            modelBuilder.Entity("Domain.Transfers.TransferItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ProcessedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ReservedQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<long>("SkuId")
                        .HasColumnType("bigint");

                    b.Property<long>("TransferId")
                        .HasColumnType("bigint");

                    b.Property<string>("Unit")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("SkuId");

                    b.HasIndex("TransferId");

                    b.ToTable("TransferItems", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Model.StockReservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("SkuId")
                        .HasColumnType("bigint");

                    b.Property<long>("TransferId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SkuId");

                    b.HasIndex("TransferId");

                    b.ToTable("StockReservations", (string)null);
                });

            modelBuilder.Entity("Domain.Model.AccessImportLog", b =>
                {
                    b.HasOne("Domain.Model.DataImportBatch", "Batch")
                        .WithMany("LogEntries")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Domain.Model.Analytics.AnalyticsSaleLineCostSnapshot", b =>
                {
                    b.HasOne("Domain.Model.Analytics.AnalyticsCostSnapshotBatch", "Batch")
                        .WithMany("Snapshots")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Domain.Model.Povracaj.PovracajStavka", b =>
                {
                    b.HasOne("Domain.Model.Povracaj.PovracajZaglavlje", "Povracaj")
                        .WithMany("Stavke")
                        .HasForeignKey("IdPovracaj")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Povracaj");
                });

            modelBuilder.Entity("Domain.Model.Prodaja.ProdajaStavka", b =>
                {
                    b.HasOne("Domain.Model.Prodaja.ProdajaZaglavlje", "Prodaja")
                        .WithMany("Stavke")
                        .HasForeignKey("IdProdaja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prodaja");
                });

            modelBuilder.Entity("Domain.Model.ProductImage", b =>
                {
                    b.HasOne("Domain.Model.Artikli", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Transfers.TransferItem", b =>
                {
                    b.HasOne("Domain.Transfers.Transfer", null)
                        .WithMany("Items")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Model.Analytics.AnalyticsCostSnapshotBatch", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Domain.Model.Artikli", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Domain.Model.DataImportBatch", b =>
                {
                    b.Navigation("LogEntries");
                });

            modelBuilder.Entity("Domain.Model.Povracaj.PovracajZaglavlje", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("Domain.Model.Prodaja.ProdajaZaglavlje", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("Domain.Transfers.Transfer", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
