using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

using Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TrendplusDbContext))]
    [Migration("20260326170000_ReconcileDataImportBatchesSchema")]
    public partial class ReconcileDataImportBatchesSchema_20260326170000 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "DataImportBatches" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
                );

                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "SourceSystem" character varying(64) NOT NULL DEFAULT 'access';
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "SourceFileName" character varying(300) NOT NULL DEFAULT '';
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "SourceFilePath" character varying(800);
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "QueuedAtUtc" timestamp with time zone NOT NULL DEFAULT NOW();
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "StartedAtUtc" timestamp with time zone NOT NULL DEFAULT NOW();
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "CompletedAtUtc" timestamp with time zone;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "LastHeartbeatUtc" timestamp with time zone;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "Status" character varying(32) NOT NULL DEFAULT 'pending';
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "CurrentStep" character varying(64);
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "CurrentTable" character varying(300);
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "SummaryJson" text;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "ErrorMessage" character varying(4000);
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "ErrorDetailsJson" text;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "RequestedBy" character varying(200);
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "ImportMode" character varying(16) NOT NULL DEFAULT 'auto';
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "IncludeAnalytics" boolean NOT NULL DEFAULT TRUE;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "OverwriteExisting" boolean NOT NULL DEFAULT TRUE;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "IncludeTemporaryTables" boolean NOT NULL DEFAULT FALSE;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "SkipInvalidForeignKeys" boolean NOT NULL DEFAULT TRUE;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "CancellationRequested" boolean NOT NULL DEFAULT FALSE;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "CancellationRequestedAtUtc" timestamp with time zone;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "RetryCount" integer NOT NULL DEFAULT 0;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "ProgressPercent" integer NOT NULL DEFAULT 0;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "RowsRead" integer NOT NULL DEFAULT 0;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "RowsAccepted" integer NOT NULL DEFAULT 0;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "RowsWritten" integer NOT NULL DEFAULT 0;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "DurationSeconds" integer;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "TotalImported" integer NOT NULL DEFAULT 0;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "TotalUpdated" integer NOT NULL DEFAULT 0;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "TotalErrors" integer NOT NULL DEFAULT 0;
                ALTER TABLE IF EXISTS "DataImportBatches" ADD COLUMN IF NOT EXISTS "DataOrigin" character varying(32) NOT NULL DEFAULT 'access';

                CREATE INDEX IF NOT EXISTS "IX_DataImportBatches_StartedAtUtc" ON "DataImportBatches" ("StartedAtUtc");
                CREATE INDEX IF NOT EXISTS "IX_DataImportBatches_QueuedAtUtc" ON "DataImportBatches" ("QueuedAtUtc");
                CREATE INDEX IF NOT EXISTS "IX_DataImportBatches_LastHeartbeatUtc" ON "DataImportBatches" ("LastHeartbeatUtc");
                CREATE INDEX IF NOT EXISTS "IX_DataImportBatches_Status" ON "DataImportBatches" ("Status");
                CREATE INDEX IF NOT EXISTS "IX_DataImportBatches_CancellationRequested" ON "DataImportBatches" ("CancellationRequested");
                """);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Intentionally left as no-op:
            // this migration reconciles existing schema drift and should be safe to keep.
        }
    }
}
