using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddWorkerRuntimeSettings : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_AccessImportCursors_TableKey_LeaseExpiresAtUtc",
                table: "AccessImportCursors");

            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "WorkerRuntimeSettings" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    "WorkerName" character varying(200) NOT NULL,
                    "IsScheduleEnabled" boolean NOT NULL DEFAULT TRUE,
                    "IsManuallyStopped" boolean NOT NULL DEFAULT FALSE,
                    "UpdatedAtUtc" timestamp with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
                    "UpdatedBy" character varying(200),
                    "Notes" character varying(1000),
                    CONSTRAINT "PK_WorkerRuntimeSettings" PRIMARY KEY ("Id")
                );

                CREATE INDEX IF NOT EXISTS "IX_WorkerRuntimeSettings_UpdatedAtUtc"
                    ON "WorkerRuntimeSettings" ("UpdatedAtUtc");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_WorkerRuntimeSettings_WorkerName"
                    ON "WorkerRuntimeSettings" ("WorkerName");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "WorkerRuntimeSettings");

            migrationBuilder.CreateIndex(
                name: "IX_AccessImportCursors_TableKey_LeaseExpiresAtUtc",
                table: "AccessImportCursors",
                columns: new[] { "TableKey", "LeaseExpiresAtUtc" });
        }
    }
}
