// <auto-generated />
using System;
using Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(TrendplusDbContext))]
    [Migration("20260110150211_AddPovracajTables")]
    partial class AddPovracajTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Model.Artikli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("IDDobavljac")
                        .HasColumnType("integer");

                    b.Property<int?>("IDObjekat")
                        .HasColumnType("integer");

                    b.Property<int?>("IDSezona")
                        .HasColumnType("integer");

                    b.Property<int?>("IDTipObuce")
                        .HasColumnType("integer");

                    b.Property<int?>("Kolicina")
                        .HasColumnType("integer");

                    b.Property<string>("Komentar")
                        .HasColumnType("text");

                    b.Property<decimal?>("NabavnaCena")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NabavnaCenaDin")
                        .HasColumnType("numeric");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PLU")
                        .HasColumnType("text");

                    b.Property<decimal?>("ProdajnaCena")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PrvaProdajnaCena")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Artikli", (string)null);
                });

            modelBuilder.Entity("Domain.Model.CreatedIdDto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.ToTable("CreatedIds");
                });

            modelBuilder.Entity("Domain.Model.DnevnikPromena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArtikalId")
                        .HasColumnType("integer");

                    b.Property<string>("BrojRacuna")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DobavljacId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Komentar")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("KorisnikIme")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("NovaProdajnaCena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("StaraProdajnaCena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipPromene")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("DnevnikPromena", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Dobavljac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .HasColumnType("text");

                    b.Property<string>("Napomena")
                        .HasColumnType("text");

                    b.Property<string>("Naziv")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dobavljaci");
                });

            modelBuilder.Entity("Domain.Model.ErrorRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientApp")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Path")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ErrorRecords", (string)null);
                });

            modelBuilder.Entity("Domain.Model.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("boolean");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsProcessed");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Povracaj.PovracajStavka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cena");

                    b.Property<int>("IdArtikal")
                        .HasColumnType("integer")
                        .HasColumnName("id_artikal");

                    b.Property<int>("IdPovracaj")
                        .HasColumnType("integer")
                        .HasColumnName("id_povracaj");

                    b.Property<int>("Kolicina")
                        .HasColumnType("integer")
                        .HasColumnName("kolicina");

                    b.Property<string>("Razlog")
                        .HasColumnType("text")
                        .HasColumnName("razlog");

                    b.Property<string>("StanjeArtikla")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stanje_artikla");

                    b.HasKey("Id");

                    b.HasIndex("IdArtikal");

                    b.HasIndex("IdPovracaj");

                    b.ToTable("povracaj_stavke", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Povracaj.PovracajZaglavlje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojZapisnika")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("broj_zapisnika");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datum_kreiranja");

                    b.Property<DateTime?>("DatumOdobrenja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datum_odobrenja");

                    b.Property<DateTime>("DatumPovracaja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datum_povracaja");

                    b.Property<int>("IDDobavljac")
                        .HasColumnType("integer")
                        .HasColumnName("id_dobavljac");

                    b.Property<string>("Komentar")
                        .HasColumnType("text")
                        .HasColumnName("komentar");

                    b.Property<string>("KreatorKorisnik")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("kreirao_korisnik");

                    b.Property<string>("OdobrioKorisnik")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("odobrio_korisnik");

                    b.Property<string>("RazlogPovracaja")
                        .HasColumnType("text")
                        .HasColumnName("razlog_povracaja");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("UkupanIznos")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ukupan_iznos");

                    b.HasKey("Id");

                    b.HasIndex("BrojZapisnika")
                        .IsUnique();

                    b.HasIndex("DatumPovracaja");

                    b.HasIndex("IDDobavljac");

                    b.ToTable("povracaj_zaglavlje", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Prodaja.ProdajaStavka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cena");

                    b.Property<int>("IdArtikal")
                        .HasColumnType("integer")
                        .HasColumnName("id_artikal");

                    b.Property<int>("IdProdaja")
                        .HasColumnType("integer")
                        .HasColumnName("id_prodaja");

                    b.Property<int>("Kolicina")
                        .HasColumnType("integer")
                        .HasColumnName("kolicina");

                    b.HasKey("Id");

                    b.HasIndex("IdProdaja");

                    b.ToTable("prodaja_stavke", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Prodaja.ProdajaZaglavlje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojRacuna")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("broj_racuna");

                    b.Property<DateTime>("DatumProdaje")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datum_prodaje");

                    b.Property<int?>("IDObjekat")
                        .HasColumnType("integer")
                        .HasColumnName("id_objekat");

                    b.Property<string>("NacinPlacanja")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nacin_placanja");

                    b.HasKey("Id");

                    b.ToTable("prodaja_zaglavlje", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Sezona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Sezone", (string)null);
                });

            modelBuilder.Entity("Domain.Model.TipObuce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoviObuce");
                });

            modelBuilder.Entity("Domain.Model.Povracaj.PovracajStavka", b =>
                {
                    b.HasOne("Domain.Model.Povracaj.PovracajZaglavlje", "Povracaj")
                        .WithMany("Stavke")
                        .HasForeignKey("IdPovracaj")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Povracaj");
                });

            modelBuilder.Entity("Domain.Model.Prodaja.ProdajaStavka", b =>
                {
                    b.HasOne("Domain.Model.Prodaja.ProdajaZaglavlje", "Prodaja")
                        .WithMany("Stavke")
                        .HasForeignKey("IdProdaja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prodaja");
                });

            modelBuilder.Entity("Domain.Model.Povracaj.PovracajZaglavlje", b =>
                {
                    b.Navigation("Stavke");
                });

            modelBuilder.Entity("Domain.Model.Prodaja.ProdajaZaglavlje", b =>
                {
                    b.Navigation("Stavke");
                });
#pragma warning restore 612, 618
        }
    }
}
