using Infrastructure.DbContexts;
using Infrastructure.Logging;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Npgsql;

namespace Infrastructure.Services;

public static class WorkerRuntimeSettingsSchemaGuard
{
    private static readonly SemaphoreSlim EnsureLock = new(1, 1);
    private static volatile bool _schemaReady;
    private static volatile bool _schemaMissing;
    private static int _missingSchemaLogCount;
    private static string? _lastTargetKey;
    private static DateTimeOffset? _lastEnsureAttemptUtc;
    private static DateTimeOffset? _lastEnsureSuccessUtc;
    private static string? _lastEnsureError;

    public static bool IsSchemaMissing => _schemaMissing;

    public static WorkerRuntimeSettingsSchemaStatus GetStatus()
    {
        return new WorkerRuntimeSettingsSchemaStatus(
            IsSchemaReady: _schemaReady,
            IsSchemaMissing: _schemaMissing,
            LastEnsureAttemptUtc: _lastEnsureAttemptUtc,
            LastEnsureSuccessUtc: _lastEnsureSuccessUtc,
            LastEnsureError: _lastEnsureError);
    }

    public static async Task<bool> EnsureSchemaAsync(
        TrendplusDbContext db,
        ILogger logger,
        CancellationToken ct = default)
    {
        if (!db.Database.IsRelational())
        {
            return true;
        }

        var targetKey = BuildTargetKey(db);
        if (_schemaReady && !_schemaMissing)
        {
            if (string.Equals(_lastTargetKey, targetKey, StringComparison.Ordinal))
            {
                return true;
            }
        }

        await EnsureLock.WaitAsync(ct);
        try
        {
            if (!string.Equals(_lastTargetKey, targetKey, StringComparison.Ordinal))
            {
                _schemaReady = false;
                _schemaMissing = false;
                _lastEnsureError = null;
            }

            if (_schemaReady && !_schemaMissing)
            {
                if (string.Equals(_lastTargetKey, targetKey, StringComparison.Ordinal))
                {
                    return true;
                }
            }

            _lastEnsureAttemptUtc = DateTimeOffset.UtcNow;
            var exists = await TableExistsAsync(db, ct);
            if (!exists)
            {
                const string createSql = """
                    CREATE TABLE IF NOT EXISTS "WorkerRuntimeSettings" (
                        "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "WorkerName" character varying(200) NOT NULL,
                        "IsScheduleEnabled" boolean NOT NULL DEFAULT TRUE,
                        "IsManuallyStopped" boolean NOT NULL DEFAULT FALSE,
                        "UpdatedAtUtc" timestamp with time zone NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
                        "UpdatedBy" character varying(200),
                        "Notes" character varying(1000)
                    );

                    CREATE UNIQUE INDEX IF NOT EXISTS "IX_WorkerRuntimeSettings_WorkerName"
                        ON "WorkerRuntimeSettings" ("WorkerName");

                    CREATE INDEX IF NOT EXISTS "IX_WorkerRuntimeSettings_UpdatedAtUtc"
                        ON "WorkerRuntimeSettings" ("UpdatedAtUtc");
                    """;

                var sw = System.Diagnostics.Stopwatch.StartNew();
                await db.Database.ExecuteSqlRawAsync(createSql, ct);
                sw.Stop();
                try
                {
                    SqlCommandLoggingHelper.LogSqlExecution(
                        "worker-runtime-settings",
                        "ExecuteSqlRaw",
                        createSql,
                        null,
                        sw.ElapsedMilliseconds,
                        true,
                        null,
                        null,
                        Application.Logging.RequestLogContext.Current.RequestId,
                        Application.Logging.RequestLogContext.Current.TraceId);
                }
                catch { }
            }

            _schemaReady = true;
            _schemaMissing = false;
            _lastTargetKey = targetKey;
            _lastEnsureSuccessUtc = DateTimeOffset.UtcNow;
            _lastEnsureError = null;
            return true;
        }
        catch (Exception ex) when (IsMissingRelationException(ex))
        {
            ReportMissingSchema(logger, ex, "ensure");
            return false;
        }
        catch (Exception ex)
        {
            _schemaReady = false;
            _schemaMissing = true;
            _lastEnsureError = ex.GetBaseException().Message;
            logger.LogWarning(ex, "Worker runtime settings schema ensure failed due to database error.");
            return false;
        }
        finally
        {
            EnsureLock.Release();
        }
    }

    public static void ReportMissingSchema(
        ILogger logger,
        Exception ex,
        string operation)
    {
        _schemaReady = false;
        _schemaMissing = true;
        _lastEnsureError = ex.GetBaseException().Message;

        if (Interlocked.Increment(ref _missingSchemaLogCount) == 1)
        {
            logger.LogError(
                ex,
                "Worker runtime settings schema is missing or not applied. Operation={Operation}. " +
                "Runtime policy will use safe fallback until schema is available.",
                operation);
            return;
        }

        logger.LogDebug(
            "Worker runtime settings schema is still missing. Operation={Operation}. Error={Error}",
            operation,
            ex.GetBaseException().Message);
    }

    public static bool IsMissingRelationException(Exception ex)
    {
        var current = ex;
        while (current is not null)
        {
            if (current is PostgresException pg &&
                pg.SqlState == "42P01" &&
                ReferencesWorkerRuntimeSettings(pg))
            {
                return true;
            }

            current = current.InnerException;
        }

        return false;
    }

    private static bool ReferencesWorkerRuntimeSettings(PostgresException ex)
    {
        if (!string.IsNullOrWhiteSpace(ex.TableName) &&
            ex.TableName.Contains("WorkerRuntimeSettings", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        var message = ex.MessageText ?? ex.Message;
        return message.Contains("WorkerRuntimeSettings", StringComparison.OrdinalIgnoreCase);
    }

    private static async Task<bool> TableExistsAsync(TrendplusDbContext db, CancellationToken ct)
    {
        const string sql = """SELECT to_regclass('public."WorkerRuntimeSettings"') IS NOT NULL;""";
        await using var connection = new NpgsqlConnection(db.Database.GetConnectionString() ?? db.Database.GetDbConnection().ConnectionString);
        await connection.OpenAsync(ct);
        await using var command = new NpgsqlCommand(sql, connection);
        command.CommandTimeout = 10;
        var sw = System.Diagnostics.Stopwatch.StartNew();
        var result = await command.ExecuteScalarAsync(ct);
        sw.Stop();
        try
        {
            SqlCommandLoggingHelper.LogSqlExecution(
                "worker-runtime-settings",
                "ExecuteScalar",
                sql,
                null,
                sw.ElapsedMilliseconds,
                true,
                null,
                null,
                Application.Logging.RequestLogContext.Current.RequestId,
                Application.Logging.RequestLogContext.Current.TraceId);
        }
        catch { }
        return result is bool exists && exists;
    }

    private static string BuildTargetKey(TrendplusDbContext db)
    {
        var cs = db.Database.GetConnectionString() ?? db.Database.GetDbConnection().ConnectionString;
        if (string.IsNullOrWhiteSpace(cs))
        {
            return "<unknown>";
        }

        try
        {
            var builder = new NpgsqlConnectionStringBuilder(cs);
            return $"{builder.Host}:{builder.Port}/{builder.Database}:{builder.Username}";
        }
        catch
        {
            return "<invalid>";
        }
    }
}

public sealed record WorkerRuntimeSettingsSchemaStatus(
    bool IsSchemaReady,
    bool IsSchemaMissing,
    DateTimeOffset? LastEnsureAttemptUtc,
    DateTimeOffset? LastEnsureSuccessUtc,
    string? LastEnsureError);
