import { z } from "zod";

const finiteNumber = z.number().finite();
const nonNegativeNumber = finiteNumber.min(0);
const nonNegativeInteger = finiteNumber.int().min(0);
const percentage = finiteNumber.min(-100).max(100);
const nonNegativePercentage = finiteNumber.min(0).max(100);
const validDate = z.string().min(1).refine((value) => Number.isFinite(Date.parse(value)), "Must be a valid date.");
const nullableNumber = finiteNumber.nullable();
const nullableSignedInteger = finiteNumber.int().nullable();
const nullableNonNegativeNumber = nonNegativeNumber.nullable();
const nullableNonNegativeInteger = nonNegativeInteger.nullable();
const nullablePercentage = percentage.nullable();
const nullableNonNegativePercentage = nonNegativePercentage.nullable();

const provenanceSchema = z.object({
  kind: z.enum([
    "authoritative_backend_aggregate",
    "observed_row_value",
    "frontend_display_derivation",
    "modeled_estimated",
    "unknown",
  ]),
  authority: z.enum(["authoritative", "observed", "derived", "modeled", "unknown"]),
  actionability: z.enum(["actionable", "informational", "blocked", "unknown"]),
  unit: z.string().nullable().optional(),
  denominator: z.string().nullable().optional(),
}).passthrough();

export const analyticsResponseMetaSchema = z.object({
  success: z.boolean(),
  generatedAtUtc: validDate.optional(),
  lastRefreshAtUtc: validDate.nullable().optional(),
  requestedPeriodFromUtc: validDate.nullable().optional(),
  requestedPeriodToUtc: validDate.nullable().optional(),
  effectivePeriodFromUtc: validDate.nullable().optional(),
  effectivePeriodToUtc: validDate.nullable().optional(),
  observedPeriodFromUtc: validDate.nullable().optional(),
  observedPeriodToUtc: validDate.nullable().optional(),
  dataQualityStatus: z.string().nullable().optional(),
  recommendationAllowed: z.boolean().nullable().optional(),
  isPartial: z.boolean().optional(),
  metricProvenance: z.record(z.string(), provenanceSchema).nullable().optional(),
}).passthrough();

const optionalMeta = analyticsResponseMetaSchema.nullable().optional();

const recommendationSchema = z.object({
  confidencePct: nullableNonNegativePercentage,
  reliabilityPct: nullableNonNegativePercentage,
  dataQualityStatus: z.string(),
  reasonCodes: z.array(z.string()),
}).passthrough();

const colorRecommendationSchema = z.object({
  status: z.enum(["increase_focus", "maintain", "review", "do_not_trust", "insufficient_data"]),
  label: z.string().trim().min(1),
  summary: z.string().trim().min(1),
  confidencePct: nullableNonNegativePercentage,
  reliabilityPct: nullableNonNegativePercentage,
  dataQualityStatus: z.string().trim().min(1),
  recommendationAllowed: z.boolean(),
  reasonCodes: z.array(z.string().trim().min(1)),
}).passthrough();

const salesStatSchema = {
  preNivelacijePromet: nonNegativeNumber,
  preNivelacijeKolicina: nonNegativeNumber,
  posleNivelacijePromet: nonNegativeNumber,
  posleNivelacijeKolicina: nonNegativeNumber,
  ukupanPromet: nonNegativeNumber,
  ukupnaKolicina: nonNegativeNumber,
  previousPeriodRevenue: nullableNumber,
  previousPeriodUnits: nullableNumber,
  brojArtikalaSaNivelacijom: nonNegativeInteger,
  brojArtikalaUkupno: nonNegativeInteger,
  revenueWithCost: nonNegativeNumber,
  estimatedCostRevenue: nonNegativeNumber,
  marginContribution: finiteNumber,
  marginDataCoveragePct: nullableNonNegativePercentage,
  fallbackCostCoveragePct: nullableNonNegativePercentage,
  marginPct: percentage,
  revenueWithNivelacijaSplit: nonNegativeNumber,
  popRevenueChangePct: nullableNumber,
  popUnitsChangePct: nullableNumber,
  prePostNivelacijaRevenueImpactPct: nullableNumber,
  prePostNivelacijaUnitsImpactPct: nullableNumber,
  prePostNivelacijaRevenueCoveragePct: nullableNonNegativePercentage,
  sharePct: nullableNonNegativePercentage.optional(),
  reliabilityPct: nullableNonNegativePercentage.optional(),
  recommendation: recommendationSchema.optional(),
};

const colorSalesStatSchema = {
  preNivelacijePromet: finiteNumber,
  preNivelacijeKolicina: finiteNumber,
  posleNivelacijePromet: finiteNumber,
  posleNivelacijeKolicina: finiteNumber,
  ukupanPromet: finiteNumber,
  ukupnaKolicina: finiteNumber,
  previousPeriodRevenue: nullableNumber,
  previousPeriodUnits: nullableNumber,
  brojArtikalaSaNivelacijom: nonNegativeInteger,
  brojArtikalaUkupno: nonNegativeInteger,
  revenueWithCost: finiteNumber,
  estimatedCostRevenue: finiteNumber,
  marginContribution: finiteNumber,
  marginDataCoveragePct: nullableNonNegativePercentage,
  fallbackCostCoveragePct: nullableNonNegativePercentage,
  marginPct: nullablePercentage,
  revenueWithNivelacijaSplit: finiteNumber,
  comparablePreRevenue: finiteNumber,
  comparablePostRevenue: finiteNumber,
  comparablePreQuantity: finiteNumber,
  comparablePostQuantity: finiteNumber,
  popRevenueChangePct: nullableNumber,
  popUnitsChangePct: nullableNumber,
  prePostNivelacijaRevenueImpactPct: nullableNumber,
  prePostNivelacijaUnitsImpactPct: nullableNumber,
  prePostNivelacijaRevenueCoveragePct: nullableNonNegativePercentage,
  prePostSignalNote: z.string().nullable(),
  prePostComparableArticleCount: nonNegativeInteger,
  sharePct: nullableNonNegativePercentage.optional(),
  decisionScore: nullableNonNegativePercentage.optional(),
  reliabilityPct: nullableNonNegativePercentage.optional(),
  recommendation: colorRecommendationSchema,
};

const costTotalsSchema = {
  ukupanPromet: nonNegativeNumber,
  ukupanMarzniDoprinos: finiteNumber,
  prePromet: nonNegativeNumber,
  poslePromet: nonNegativeNumber,
  ukupnaKolicina: nonNegativeNumber,
  preKolicina: nonNegativeNumber,
  posleKolicina: nonNegativeNumber,
  previousPeriodRevenue: nullableNumber,
  previousPeriodUnits: nullableNumber,
  popRevenueChangePct: nullableNumber,
  popUnitsChangePct: nullableNumber,
  prePostNivelacijaRevenueImpactPct: nullableNumber,
  prePostNivelacijaUnitsImpactPct: nullableNumber,
};

const colorCostTotalsSchema = {
  ...costTotalsSchema,
  ukupanPromet: finiteNumber,
  prePromet: finiteNumber,
  poslePromet: finiteNumber,
  ukupnaKolicina: finiteNumber,
  preKolicina: finiteNumber,
  posleKolicina: finiteNumber,
  comparablePreRevenue: finiteNumber,
  comparablePostRevenue: finiteNumber,
  comparablePreQuantity: finiteNumber,
  comparablePostQuantity: finiteNumber,
  comparableArticleCount: nonNegativeInteger,
  comparableRevenueCoveragePct: nullableNonNegativePercentage,
  prePostSignalNote: z.string().nullable(),
  observedPreRevenue: finiteNumber,
  observedPostRevenue: finiteNumber,
  observedPreQuantity: finiteNumber,
  observedPostQuantity: finiteNumber,
  weightedKnownMarginPct: nullableNumber,
  weightedKnownMarginRevenue: finiteNumber,
  decisionScore: nullableNonNegativePercentage.optional(),
  recommendationSummary: z.object({
    increaseFocus: nonNegativeInteger,
    maintain: nonNegativeInteger,
    review: nonNegativeInteger,
    doNotTrust: nonNegativeInteger,
    insufficientData: nonNegativeInteger,
  }),
};

const colorDataQualitySchema = z.object({
  missingCostRevenue: finiteNumber,
  missingCostRevenueSharePct: nullableNonNegativePercentage,
  estimatedCostRevenue: finiteNumber.optional(),
  estimatedCostRevenueSharePct: nullableNonNegativePercentage.optional(),
  unknownColorRevenue: finiteNumber,
  unknownColorRevenueSharePct: nullableNonNegativePercentage,
  revenueWithNivelacijaSplit: finiteNumber,
  revenueWithNivelacijaSplitSharePct: nullableNonNegativePercentage,
  observedRevenueWithNivelacijaSplit: finiteNumber,
  observedRevenueWithNivelacijaSplitSharePct: nullableNonNegativePercentage,
  signedRevenuePolicy: z.string().optional(),
  signedQuantityPolicy: z.string().optional(),
  costQualityDenominatorStatus: z.string().optional(),
  weightedKnownMarginPct: nullableNumber,
  weightedKnownMarginRevenue: finiteNumber,
}).passthrough();

const shoeTypeRecommendationSchema = z.object({
  status: z.enum(["increase_focus", "maintain", "review", "do_not_trust", "insufficient_data"]),
  label: z.string().trim().min(1),
  summary: z.string().trim().min(1),
  confidencePct: nullableNonNegativePercentage,
  reliabilityPct: nullableNonNegativePercentage,
  dataQualityStatus: z.enum(["good", "warning", "critical", "insufficient_data"]),
  recommendationAllowed: z.boolean(),
  reasonCodes: z.array(z.string().trim().min(1)),
});

const shoeDataQualitySchema = z.object({
  costCoveredRevenue: nonNegativeNumber,
  costCoveredRevenueSharePct: nullableNonNegativePercentage,
  missingCostRevenue: nonNegativeNumber,
  missingCostRevenueSharePct: nullableNonNegativePercentage,
  noCostRevenue: nonNegativeNumber,
  noCostRevenueSharePct: nullableNonNegativePercentage,
  historicalCostRevenue: nonNegativeNumber,
  historicalCostRevenueSharePct: nullableNonNegativePercentage,
  snapshotCostRevenue: nonNegativeNumber,
  snapshotCostRevenueSharePct: nullableNonNegativePercentage,
  estimatedCostRevenue: nonNegativeNumber.optional(),
  estimatedCostRevenueSharePct: nullableNonNegativePercentage.optional(),
  revenueWithNivelacijaSplit: nonNegativeNumber,
  revenueWithNivelacijaSplitSharePct: nullableNonNegativePercentage,
  unknownTypeRevenue: nonNegativeNumber,
  unknownTypeRevenueSharePct: nullableNonNegativePercentage,
});

const seasonSchema = z.object({
  id: nonNegativeInteger,
  naziv: z.string(),
  datumOd: validDate,
  datumDo: validDate,
}).passthrough();

export const colorSalesStatsResponseSchema = z.object({
  generatedAt: validDate,
  meta: analyticsResponseMetaSchema,
  fromDate: validDate.nullable(),
  toDate: validDate.nullable(),
  dataWindowFrom: validDate.nullable(),
  dataWindowTo: validDate.nullable(),
  sezonaId: nonNegativeInteger.nullable(),
  storeId: nonNegativeInteger.nullable(),
  dataScope: z.enum(["all", "existing", "imported"]),
  lineage: z.object({
    storeId: nonNegativeInteger.nullable(),
    dataScope: z.string(),
    sourceFamily: z.string().trim().min(1).optional(),
    sourceLabel: z.string().trim().min(1).optional(),
    sourceTables: z.string().trim().min(1).optional(),
    observedPopulation: z.string().trim().min(1).optional(),
    costPolicy: z.string().trim().min(1).optional(),
    prePostPolicy: z.string().trim().min(1).optional(),
    unknownPolicy: z.string().trim().min(1).optional(),
    eventCount: nonNegativeInteger,
    eventArticleCount: nonNegativeInteger,
    salesArticleCount: nonNegativeInteger,
    salesArticlesWithMatchingNivelacija: nonNegativeInteger,
    storePolicy: z.string(),
    originPolicy: z.string(),
  }),
  colors: z.array(z.object({
    boja: z.string(),
    ...colorSalesStatSchema,
  }).passthrough()),
  totals: z.object(colorCostTotalsSchema).passthrough(),
  dataQuality: colorDataQualitySchema,
  sezone: z.array(seasonSchema),
}).passthrough();

export const shoeTypeSalesStatsResponseSchema = z.object({
  generatedAt: validDate,
  meta: optionalMeta,
  fromDate: validDate.nullable(),
  toDate: validDate.nullable(),
  dataWindowFrom: validDate.nullable(),
  dataWindowTo: validDate.nullable(),
  sezonaId: nonNegativeInteger.nullable(),
  storeId: nonNegativeInteger.nullable(),
  dataScope: z.string().nullable().optional(),
  shoeTypes: z.array(z.object({
    tipObuceId: nonNegativeInteger.nullable(),
    tipObuceNaziv: z.string(),
    isUnknown: z.boolean(),
    ...salesStatSchema,
    costCoveredRevenue: nonNegativeNumber,
    costCoveredRevenueSharePct: nullableNonNegativePercentage,
    marginPct: nullablePercentage,
    totalCost: finiteNumber,
    historicalCostRevenue: nonNegativeNumber,
    historicalCostCoveragePct: nullableNonNegativePercentage,
    estimatedCostCoveragePct: nullableNonNegativePercentage,
    snapshotCostRevenue: nonNegativeNumber,
    snapshotCostCoveragePct: nullableNonNegativePercentage,
    noCostRevenue: nonNegativeNumber,
    noCostCoveragePct: nullableNonNegativePercentage,
    isEstimatedMargin: z.boolean(),
    marginQualityLabel: z.string().nullable(),
    marginQualityTier: z.string().nullable(),
    marginQualityShortLabel: z.string().nullable(),
    marginQualityTooltip: z.string().nullable(),
    recommendation: shoeTypeRecommendationSchema,
    comparableRevenueWithNivelacijaSplit: nonNegativeNumber,
    comparablePreRevenue: nonNegativeNumber,
    comparablePostRevenue: nonNegativeNumber,
    comparablePreQuantity: nonNegativeInteger,
    comparablePostQuantity: nonNegativeInteger,
    prePostSignalNote: z.string().nullable(),
    prePostComparableArticleCount: nonNegativeInteger,
    promenaPrometa: nullableNumber,
    promenaKolicine: nullableNumber,
  })),
  totals: z.object({
    ...costTotalsSchema,
    brojTipovaObuce: nonNegativeInteger,
    ukupanTrosak: finiteNumber,
    prosecnaMarza: nullablePercentage,
    weightedMarginRevenue: nullableNonNegativeNumber,
    historicalCostCoveragePct: nullableNonNegativePercentage,
    estimatedCostCoveragePct: nullableNonNegativePercentage,
    noCostCoveragePct: nullableNonNegativePercentage,
    snapshotCostRevenue: nonNegativeNumber,
    snapshotCostCoveragePct: nullableNonNegativePercentage,
    isSnapshotActive: z.boolean(),
    snapshotGeneratedAtUtc: validDate.nullable(),
    isEstimatedMargin: z.boolean(),
    marginQualityLabel: z.string().nullable(),
    marginQualityTier: z.string().nullable(),
    marginQualityShortLabel: z.string().nullable(),
    marginQualityTooltip: z.string().nullable(),
    comparablePreRevenue: nonNegativeNumber,
    comparablePostRevenue: nonNegativeNumber,
    comparablePreQuantity: nonNegativeInteger,
    comparablePostQuantity: nonNegativeInteger,
    comparableArticleCount: nonNegativeInteger,
    comparableRevenueCoveragePct: nullableNonNegativePercentage,
    observedPreRevenue: nonNegativeNumber,
    observedPostRevenue: nonNegativeNumber,
    observedPreQuantity: nonNegativeInteger,
    observedPostQuantity: nonNegativeInteger,
  }),
  dataQuality: shoeDataQualitySchema,
  sezone: z.array(seasonSchema),
}).passthrough();

const vendorSalesNivelacijaRecommendationSchema = z.object({
  status: z.enum(["increase_focus", "maintain", "review", "do_not_trust", "insufficient_data"]),
  label: z.string().trim().min(1),
  summary: z.string(),
  confidencePct: nullableNonNegativePercentage,
  reliabilityPct: nullableNonNegativePercentage,
  dataQualityStatus: z.string().trim().min(1),
  recommendationAllowed: z.boolean().nullable().optional(),
  reasonCodes: z.array(z.string().trim().min(1)),
}).passthrough();

const vendorSalesNivelacijaVendorSchema = z.object({
  vendorId: nullableSignedInteger,
  vendorName: z.string(),
  preQty: finiteNumber,
  preRevenue: finiteNumber,
  postQty: finiteNumber,
  postRevenue: finiteNumber,
  changeQty: finiteNumber,
  changeRevenue: finiteNumber,
  changePercent: finiteNumber,
  absoluteChangeRevenue: finiteNumber,
  changeSharePercent: finiteNumber,
  postRevenueSharePercent: finiteNumber,
  avgCoveragePre30: nullableNonNegativePercentage,
  avgCoveragePost30: nullableNonNegativePercentage,
  hasComparableSalesWindow: z.boolean().optional(),
  semanticChangePercentRevenue: nullableNumber.optional(),
  semanticChangePercentQty: nullableNumber.optional(),
  articleCount: nonNegativeInteger,
  activeArticlesCount: nonNegativeInteger,
  increasedPriceArticlesCount: nonNegativeInteger,
  decreasedPriceArticlesCount: nonNegativeInteger,
  reliabilityPct: nullableNonNegativePercentage,
  recommendation: vendorSalesNivelacijaRecommendationSchema.nullable().optional(),
  comparableArticleCount: nonNegativeInteger.optional(),
  primaryFootwearType: z.string().nullable().optional(),
  primaryFootwearTypeSharePercent: nullableNonNegativePercentage.optional(),
  primaryFootwearTypeAvgElasticity: nullableNumber.optional(),
  typeInsightsAuthoritative: z.boolean().optional(),
}).passthrough();

const vendorSalesNivelacijaArticleSchema = z.object({
  eventDate: validDate,
  vendorId: nullableSignedInteger,
  vendorName: z.string(),
  sku: z.string(),
  articleName: z.string(),
  category: z.string(),
  oldPrice: nullableNumber,
  newPrice: nullableNumber,
  preQty: finiteNumber,
  preRevenue: finiteNumber,
  postQty: finiteNumber,
  postRevenue: finiteNumber,
  changeQty: finiteNumber,
  changeRevenue: finiteNumber,
  changePercent: nullableNumber,
  coveragePre30: nullableNonNegativePercentage,
  coveragePost30: nullableNonNegativePercentage,
  hasSalesWindow: z.boolean(),
  hasPreSalesEvidence: z.boolean().optional(),
  hasPostSalesEvidence: z.boolean().optional(),
  hasComparableSalesWindow: z.boolean().optional(),
  hasQtyBaseline: z.boolean().optional(),
  qtyBaselineReason: z.string().nullable().optional(),
  hasRevenueBaseline: z.boolean().optional(),
  revenueBaselineReason: z.string().nullable().optional(),
  semanticChangePercentRevenue: nullableNumber.optional(),
  semanticChangePercentQty: nullableNumber.optional(),
  priceChanged: z.boolean(),
  priceChangePercent: nullableNumber,
  rolling7dPreRevenue: nullableNumber.optional(),
  rolling7dPostRevenue: nullableNumber.optional(),
  momentumRevenue: nullableNumber.optional(),
  priceElasticity: nullableNumber.optional(),
  didRevenue: nullableNumber.optional(),
  didQty: nullableNumber.optional(),
  lostSalesOOS: nullableNumber.optional(),
  oosRate: nullableNonNegativePercentage.optional(),
  metricReason: z.string().nullable().optional(),
}).passthrough();

const vendorSalesNivelacijaTotalsSchema = z.object({
  preQty: finiteNumber,
  preRevenue: finiteNumber,
  postQty: finiteNumber,
  postRevenue: finiteNumber,
  changeQty: finiteNumber,
  changeRevenue: finiteNumber,
  changePercent: finiteNumber,
  vendorsCount: nonNegativeInteger,
  articlesCount: nonNegativeInteger,
  activeArticlesCount: nonNegativeInteger,
  avgRevenuePerArticlePre: finiteNumber,
  avgRevenuePerArticlePost: finiteNumber,
  avgPriceChangePercent: finiteNumber,
  absoluteChangeRevenue: finiteNumber,
  avgCoveragePre30: nullableNonNegativePercentage,
  avgCoveragePost30: nullableNonNegativePercentage,
  hasComparableSalesWindow: z.boolean(),
  comparableRows: nonNegativeInteger,
  comparableArticlesCount: nonNegativeInteger,
  comparableVendorsCount: nonNegativeInteger,
}).passthrough();

const vendorSalesNivelacijaDataQualitySchema = z.object({
  rawRows: nullableNonNegativeInteger,
  deduplicatedRows: nullableNonNegativeInteger,
  duplicateRowsRemoved: nullableNonNegativeInteger,
  cohortRows: nullableNonNegativeInteger.optional(),
  cohortRowsExcluded: nullableNonNegativeInteger.optional(),
  returnedRows: nullableNonNegativeInteger.optional(),
  truncatedRows: nullableNonNegativeInteger.optional(),
  comparableRows: nullableNonNegativeInteger.optional(),
  comparableSharePercent: nullableNonNegativePercentage.optional(),
  isDetailTruncated: z.boolean().nullable().optional(),
  cohortPolicy: z.string().nullable().optional(),
  inactiveRows: nullableNonNegativeInteger,
  unchangedPriceRows: nullableNonNegativeInteger,
  analyzedRows: nullableNonNegativeInteger,
  analyzedSharePercent: nullableNonNegativePercentage,
  lowPostCoverageRows: nullableNonNegativeInteger,
  avgCoveragePre30: nullableNonNegativePercentage,
  avgCoveragePost30: nullableNonNegativePercentage,
}).passthrough();

const vendorSalesNivelacijaCategorySchema = z.object({
  category: z.string(),
  articlesCount: nonNegativeInteger,
  vendorsCount: nonNegativeInteger,
  preQty: finiteNumber,
  preRevenue: finiteNumber,
  postQty: finiteNumber,
  postRevenue: finiteNumber,
  changeQty: finiteNumber,
  changeRevenue: finiteNumber,
  changePercent: finiteNumber,
  hasComparableSalesWindow: z.boolean(),
  comparableArticleCount: nonNegativeInteger,
  postRevenueSharePercent: nullableNonNegativePercentage.optional(),
  avgElasticity: nullableNumber.optional(),
}).passthrough();

const vendorSalesNivelacijaPriceDirectionSchema = z.object({
  segment: z.string(),
  articlesCount: nonNegativeInteger,
  vendorsCount: nonNegativeInteger,
  avgPriceChangePercent: finiteNumber,
  changeRevenue: finiteNumber,
  changePercent: finiteNumber,
  hasComparableSalesWindow: z.boolean(),
  comparableArticleCount: nonNegativeInteger,
}).passthrough();

const vendorSalesNivelacijaInsightSchema = z.object({
  title: z.string(),
  value: z.string(),
  details: z.string(),
  tone: z.string(),
}).passthrough();

export const vendorSalesNivelacijaResponseSchema = z.object({
  generatedAt: validDate,
  windowDays: nullableNonNegativeInteger,
  vendorId: nullableSignedInteger,
  eventDate: validDate.nullable(),
  from: validDate.nullable(),
  to: validDate.nullable(),
  category: z.string().nullable(),
  includeInactive: z.boolean(),
  storeId: nullableSignedInteger,
  dataScope: z.enum(["all", "existing", "imported"]),
  scopeApplied: z.boolean(),
  categories: z.array(z.string()),
  vendorStats: z.array(vendorSalesNivelacijaVendorSchema),
  articleStats: z.array(vendorSalesNivelacijaArticleSchema),
  totals: vendorSalesNivelacijaTotalsSchema,
  dataQuality: vendorSalesNivelacijaDataQualitySchema.nullable().optional(),
  categoryStats: z.array(vendorSalesNivelacijaCategorySchema),
  typeInsightsAuthoritative: z.boolean().optional(),
  typeInsightsSource: z.string().nullable().optional(),
  typeInsightsDenominator: z.string().nullable().optional(),
  priceDirectionStats: z.array(vendorSalesNivelacijaPriceDirectionSchema),
  insights: z.array(vendorSalesNivelacijaInsightSchema),
  avgMomentumRevenue: nullableNumber.optional(),
  avgElasticity: nullableNumber.optional(),
  avgDidRevenue: nullableNumber.optional(),
  avgLostSalesOOS: nullableNumber.optional(),
  oosRate: nullableNonNegativePercentage.optional(),
  metricsStatus: z.string().nullable().optional(),
  recommendationAllowed: z.boolean().nullable().optional(),
  meta: optionalMeta,
}).passthrough();

export const vendorSalesNivelacijaOptionsSchema = z.array(z.object({
  eventDate: validDate,
  eventsCount: nonNegativeInteger,
  vendorsCount: nullableNonNegativeInteger,
  articlesCount: nullableNonNegativeInteger,
  activeArticlesCount: nullableNonNegativeInteger,
  hasSalesWindow: z.boolean(),
  label: z.string(),
}).passthrough());

const dailySalesRowSchema = z.object({
  date: validDate,
  firstShiftTotalItems: nullableNumber,
  secondShiftTotalItems: nullableNumber,
  totalRevenue: nullableNumber,
  topSupplierCounts: z.array(nullableNumber),
  othersCount: nullableNumber,
  totalItemsSold: nullableNumber,
}).passthrough();

const dailySalesMetadataSchema = z.object({
  totalDays: nullableNonNegativeInteger,
  uniqueSuppliersInRange: nullableNonNegativeInteger,
  // Quantities and derived ratios use net signed sales evidence: returns and
  // corrections can legitimately make these values negative.
  unknownSupplierPct: nullableNumber,
  unknownSupplierItems: nullableSignedInteger,
  offShiftItems: nullableSignedInteger,
  offShiftRevenue: nullableNumber,
  totalItemsInRange: nullableSignedInteger,
  duplicateReceiptGroupCount: nullableNonNegativeInteger,
  duplicateReceiptHeaderCount: nullableNonNegativeInteger,
  receiptAmountMismatchCount: nullableNonNegativeInteger,
  receiptAmountMismatchRevenue: nullableNonNegativeNumber,
  nonStandardReceiptCount: nullableNonNegativeInteger,
  nonStandardReceiptRevenue: nullableNumber,
  debtReceiptCount: nullableNonNegativeInteger,
  debtReceiptRevenue: nullableNumber,
  minAvailableDate: validDate.nullable(),
  maxAvailableDate: validDate.nullable(),
  warnings: z.array(z.string()).optional(),
}).passthrough();

export const dailySalesTableResponseSchema = z.object({
  requestedFrom: validDate,
  requestedTo: validDate,
  storeId: nonNegativeInteger.nullable(),
  topN: nonNegativeInteger,
  dataScope: z.string(),
  topSuppliers: z.array(z.object({
    supplierId: nonNegativeInteger.nullable(),
    supplierName: z.string(),
    isUnknown: z.boolean(),
    totalQty: nullableNumber,
    totalRevenue: nullableNumber,
  }).passthrough()),
  topSuppliersOrder: z.array(z.string()),
  dateRows: z.array(dailySalesRowSchema),
  metadata: dailySalesMetadataSchema,
  meta: optionalMeta,
}).passthrough();

const preNivelacijaScenarioSchema = z.object({
  expectedUnits30d: nonNegativeInteger,
  expectedRevenue30d: nonNegativeNumber,
  expectedMargin30d: finiteNumber,
  effectivePrice: nonNegativeNumber,
}).passthrough();

const preNivelacijaRecommendationStatusSchema = z.enum([
  "increase_focus",
  "maintain",
  "review",
  "do_not_trust",
  "insufficient_data",
]);

const preNivelacijaQualityStatusSchema = z.enum(["good", "warning", "critical", "insufficient_data"]);
const preNivelacijaReasonCodeSchema = z.string().trim().min(1);
const preNivelacijaPriorityBandSchema = z.enum(["high", "medium", "low"]);
const preNivelacijaSalesEvidenceStatusSchema = z.enum([
  "positive_net_sales",
  "no_sales_in_window",
  "zero_net_sales",
  "negative_net_sales",
  "signed_adjustment",
  "non_positive_net_with_returns",
]);
const preNivelacijaSalesEvidenceReasonSchema = z.enum([
  "no_sales_in_window",
  "zero_net_sales",
  "negative_net_sales",
  "signed_sales_adjustment",
  "signed_sales_non_positive",
]).nullable();

const preNivelacijaRecommendationSchema = z.object({
  status: preNivelacijaRecommendationStatusSchema,
  label: z.string().trim().min(1),
  summary: z.string().trim().min(1),
  confidencePct: nonNegativePercentage,
  reliabilityPct: nullableNonNegativePercentage,
  dataQualityStatus: preNivelacijaQualityStatusSchema,
  recommendationAllowed: z.boolean(),
  reasonCodes: z.array(preNivelacijaReasonCodeSchema),
}).passthrough();

const preNivelacijaCandidateSchema = z.object({
  artikalId: nonNegativeInteger,
  sku: z.string().trim().min(1),
  supplierId: nonNegativeInteger.nullable(),
  seasonId: nonNegativeInteger.nullable(),
  footwearTypeId: nonNegativeInteger.nullable(),
  supplierName: z.string().trim().min(1),
  category: z.string().trim().min(1),
  footwearType: z.string().trim().min(1),
  season: z.string().trim().min(1),
  stockUnits: nonNegativeNumber,
  units180: finiteNumber,
  positiveUnits180: nonNegativeInteger,
  negativeUnits180: finiteNumber.int(),
  velocity180: finiteNumber,
  daysSinceLastSale: nonNegativeInteger,
  markdownEvents: nonNegativeInteger,
  avgMarkdownPct: nonNegativePercentage,
  grossMarginPctEst: percentage,
  seasonRecencyBoost: percentage,
  preNivelacijaScore: nonNegativePercentage,
  priorityBand: preNivelacijaPriorityBandSchema,
  scoreBreakdown: z.object({
    stockPressure: nonNegativePercentage,
    velocityRisk: nonNegativePercentage,
    recencyRisk: nonNegativePercentage,
    markdownOpportunity: nonNegativePercentage,
    marginPotential: nonNegativePercentage,
    seasonRecencyBoost: nonNegativePercentage,
  }).passthrough(),
  scenarioHighlightNow: preNivelacijaScenarioSchema,
  scenarioMarkdownNow: preNivelacijaScenarioSchema,
  marginDeltaHighlightVsMarkdown: finiteNumber,
  revenueDeltaHighlightVsMarkdown: finiteNumber,
  hasCompleteEvidence: z.boolean(),
  evidenceReason: z.string().nullable(),
  salesEvidenceStatus: preNivelacijaSalesEvidenceStatusSchema,
  salesEvidenceReason: preNivelacijaSalesEvidenceReasonSchema,
  confidence: z.string().trim().min(1),
  reliabilityPct: nonNegativePercentage,
  decisionScore: nonNegativePercentage,
  recommendationAllowed: z.boolean(),
  recommendation: preNivelacijaRecommendationSchema,
}).passthrough();

const preNivelacijaSupplierSchema = z.object({
  supplierId: nonNegativeInteger.nullable(),
  supplierName: z.string().trim().min(1),
  highPrioritySkuCount: nonNegativeInteger,
  candidateSkuCount: nonNegativeInteger,
  stockUnitsAtRisk: nonNegativeInteger,
  estimatedAvoidableMarkdownLoss: finiteNumber,
  expectedHighlightRevenueUplift: finiteNumber,
  actionScore: finiteNumber,
  weekOverWeekRiskDeltaPct: nullableNumber,
  weekOverWeekEvidenceStatus: z.enum(["measured", "unavailable_non_positive_denominator"]),
}).passthrough();

const preNivelacijaQueueItemSchema = z.object({
  artikalId: nonNegativeInteger,
  sku: z.string().trim().min(1),
  supplierName: z.string().trim().min(1),
  preNivelacijaScore: nonNegativePercentage,
  priorityBand: preNivelacijaPriorityBandSchema,
  owner: z.string().trim().min(1),
  status: z.string().trim().min(1),
  dueDateUtc: validDate,
}).passthrough();

const preNivelacijaAlertSchema = z.object({
  type: z.string().trim().min(1),
  severity: z.enum(["critical", "warning", "info"]),
  message: z.string().trim().min(1),
  supplierName: z.string().trim().min(1).nullable(),
  artikalId: nonNegativeInteger.nullable(),
}).passthrough();

const preNivelacijaFilterOptionSchema = z.object({
  id: nonNegativeInteger,
  label: z.string().trim().min(1),
}).passthrough();

export const preNivelacijaPriorityResponseSchema = z.object({
  generatedAtUtc: validDate,
  formulaVersion: z.string(),
  formulaDescription: z.string(),
  summary: z.object({
    supplierCount: nonNegativeInteger,
    candidatesCount: nonNegativeInteger,
    highPriorityCount: nonNegativeInteger,
    increaseFocusCount: nonNegativeInteger,
    maintainCount: nonNegativeInteger,
    reviewCount: nonNegativeInteger,
    doNotTrustCount: nonNegativeInteger,
    insufficientDataCount: nonNegativeInteger,
    totalStockAtRisk: nonNegativeNumber,
    estimatedAvoidableMarkdownLoss: finiteNumber,
    expectedHighlightRevenueUplift: finiteNumber,
    averagePreNivelacijaScore: finiteNumber,
  }).passthrough(),
  supplierLeaderboard: z.array(preNivelacijaSupplierSchema),
  filterFacets: z.object({
    seasons: z.array(preNivelacijaFilterOptionSchema),
    footwearTypes: z.array(preNivelacijaFilterOptionSchema),
  }).passthrough(),
  candidates: z.array(preNivelacijaCandidateSchema),
  queues: z.object({
    highlightNow: z.array(preNivelacijaQueueItemSchema),
    monitor: z.array(preNivelacijaQueueItemSchema),
    likelyMarkdownSoon: z.array(preNivelacijaQueueItemSchema),
  }).passthrough(),
  alerts: z.array(preNivelacijaAlertSchema),
  page: nonNegativeInteger,
  pageSize: nonNegativeInteger,
  totalCandidates: nonNegativeInteger,
  recommendationAllowed: z.boolean(),
  evidenceWindow: z.object({
    salesWindowFromUtc: validDate,
    salesWindowToUtc: validDate,
    markdownWindowFromUtc: validDate,
    markdownWindowToUtc: validDate,
    timezone: z.string(),
    salesQuantityPolicy: z.string(),
    nonPositiveNetPolicy: z.string(),
    previousWeekDenominatorPolicy: z.string(),
    candidatesWithReturns: nonNegativeInteger,
    candidatesWithNonPositiveNetSales: nonNegativeInteger,
    candidatesWithoutSalesInWindow: nonNegativeInteger,
    suppliersWithUnavailablePreviousWeekDenominator: nonNegativeInteger,
  }).nullable(),
  meta: optionalMeta,
}).passthrough();

const inventoryMetaFields = {
  meta: optionalMeta,
};

const inventoryListItemSchema = z.object({
  id: nonNegativeInteger,
  naziv: z.string(),
  kolicina: nullableNumber.optional(),
  minimalnaKolicina: nullableNumber.optional(),
  estimatedValue: nullableNumber.optional(),
  stockCoverDays: nullableNumber.optional(),
  sellThroughRatio: nullableNonNegativePercentage.optional(),
  signalConfidencePct: nullableNonNegativePercentage.optional(),
}).passthrough();

export const inventoryBalanceResponseSchema = z.object({
  totalSku: nonNegativeInteger,
  totalOnHand: nonNegativeNumber,
  lowStockCount: nonNegativeInteger,
  outOfStockCount: nonNegativeInteger,
  estimatedInventoryValue: nullableNumber.optional(),
  ...inventoryMetaFields,
}).passthrough();

export const inventoryPagedResponseSchema = z.object({
  items: z.array(inventoryListItemSchema),
  totalCount: nonNegativeInteger,
  pageNumber: nonNegativeInteger,
  pageSize: nonNegativeInteger,
  ...inventoryMetaFields,
}).passthrough();

const inventoryInsightItemSchema = z.object({
  id: nonNegativeInteger,
  storeId: z.number().int().nonnegative().nullable(),
  supplierId: z.number().int().nonnegative().nullable(),
  quantity: nonNegativeNumber,
  minimum: nonNegativeNumber,
  reorderGap: finiteNumber,
  estimatedValue: nullableNumber,
  unitCost: nullableNumber,
  costSource: z.string(),
  costMissing: z.boolean(),
  daysSinceMovement: nonNegativeNumber,
  sellThroughRatio: nullableNonNegativePercentage.optional(),
  signalConfidencePct: nonNegativePercentage,
}).passthrough();

export const inventoryInsightsResponseSchema = z.object({
  totalItems: nonNegativeInteger,
  totalEstimatedValue: nonNegativeNumber,
  aging: z.array(z.object({
    itemCount: nonNegativeInteger,
    totalUnits: nonNegativeNumber,
    estimatedValue: nonNegativeNumber,
  }).passthrough()),
  abc: z.array(z.object({
    itemCount: nonNegativeInteger,
    estimatedValue: nonNegativeNumber,
    valueSharePct: nonNegativePercentage,
  }).passthrough()),
  topAgedItems: z.array(inventoryInsightItemSchema),
  topCapitalLockedItems: z.array(inventoryInsightItemSchema),
  ...inventoryMetaFields,
}).passthrough();

export const inventoryDetailResponseSchema = z.object({
  id: nonNegativeInteger,
  estimatedValue: nonNegativeNumber,
  updatedAt: validDate,
  movementCount: nonNegativeInteger,
  daysSinceMovement: nonNegativeNumber,
  stockCoverDays: nullableNumber.optional(),
  sellThroughRatio: nullableNonNegativePercentage.optional(),
  signalConfidencePct: nonNegativePercentage,
  recommendationAllowed: z.boolean(),
  history: z.array(z.unknown()),
}).passthrough();
