-- ==========================================================
-- 013_AddSupplierDecisionCompatibilitySchema.sql
-- Analytics-side compatibility layer for supplier decision analytics.
--
-- Purpose:
-- - keep analytical reads in analytics DB
-- - expose compatibility views that mirror Trendplus operational names
-- - add missing return fact table required for supplier quality signals
-- ==========================================================

CREATE TABLE IF NOT EXISTS "ReturnFacts" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SourceLineId" integer NOT NULL,
    "ReturnId" integer NOT NULL,
    "ProductId" integer NOT NULL,
    "SupplierId" integer NOT NULL,
    "Qty" integer NOT NULL,
    "UnitCost" numeric(18,2) NOT NULL DEFAULT 0,
    "LineAmount" numeric(18,2) NOT NULL DEFAULT 0,
    "ReturnTimestampUtc" timestamp with time zone NOT NULL,
    "Status" character varying(100) NOT NULL DEFAULT '',
    "HeaderReason" character varying(500),
    "LineReason" character varying(500),
    "ItemCondition" character varying(200),
    "BrojZapisnika" character varying(100),
    "DataOrigin" character varying(32) NOT NULL DEFAULT 'existing'
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_ReturnFacts_SourceLineId"
    ON "ReturnFacts" ("SourceLineId");

CREATE INDEX IF NOT EXISTS "IX_ReturnFacts_ReturnId"
    ON "ReturnFacts" ("ReturnId");

CREATE INDEX IF NOT EXISTS "IX_ReturnFacts_ProductId"
    ON "ReturnFacts" ("ProductId");

CREATE INDEX IF NOT EXISTS "IX_ReturnFacts_SupplierId"
    ON "ReturnFacts" ("SupplierId");

CREATE INDEX IF NOT EXISTS "IX_ReturnFacts_ReturnTimestampUtc"
    ON "ReturnFacts" ("ReturnTimestampUtc");

CREATE INDEX IF NOT EXISTS "IX_ReturnFacts_SupplierId_ReturnTimestampUtc"
    ON "ReturnFacts" ("SupplierId", "ReturnTimestampUtc");

-- Dodavanje validacija
ALTER TABLE "ReturnFacts"
DROP CONSTRAINT IF EXISTS "CHK_Status";

ALTER TABLE "ReturnFacts"
ADD CONSTRAINT "CHK_Status" CHECK ("Status" IN ('Pending', 'Approved', 'Rejected'));

ALTER TABLE "ReturnFacts"
DROP CONSTRAINT IF EXISTS "CHK_DataOrigin";

ALTER TABLE "ReturnFacts"
ADD CONSTRAINT "CHK_DataOrigin" CHECK ("DataOrigin" IN ('existing', 'new'));

-- Dodavanje partial index-a
CREATE INDEX IF NOT EXISTS "IX_ReturnFacts_Timestamp_Supplier"
ON "ReturnFacts" ("ReturnTimestampUtc", "SupplierId")
WHERE "ReturnTimestampUtc" >= '2026-01-01';

CREATE OR REPLACE VIEW "Artikli" AS
WITH latest_products AS (
    SELECT DISTINCT ON ("ProductId")
        p.*
    FROM "ProductsDim" p
    ORDER BY p."ProductId", p."Timestamp" DESC, p."ProductKey" DESC
)
SELECT
    p."ProductId" AS "Id",
    COALESCE(NULLIF(p."PLU", ''), p."ProductId"::text) AS "PLU",
    p."ProductName" AS "Naziv",
    NULLIF(p."Category", '') AS "Kategorija",
    NULLIF(p."SubCategory", '') AS "Pol",
    p."FootwearTypeId" AS "IDTipObuce",
    p."SupplierId" AS "IDDobavljac",
    p."SeasonId" AS "IDSezona",
    p."PurchasePrice" AS "NabavnaCena",
    p."PurchasePriceRsd" AS "NabavnaCenaDin",
    p."FirstSalePrice" AS "PrvaProdajnaCena",
    p."SalePrice" AS "ProdajnaCena",
    p."Kolicina" AS "Kolicina",
    p."MinimalnaKolicina" AS "MinimalnaKolicina",
    p."Velicina" AS "Velicina",
    p."Boja" AS "Boja",
    p."Materijal" AS "Materijal",
    p."Timestamp" AS "UpdatedAt",
    p."DataOrigin" AS "DataOrigin"
FROM latest_products p;

CREATE OR REPLACE VIEW "Dobavljaci" AS
WITH latest_suppliers AS (
    SELECT DISTINCT ON ("SupplierId")
        s.*
    FROM "SuppliersDim" s
    ORDER BY s."SupplierId", s."UpdatedAt" DESC, s."SupplierKey" DESC
)
SELECT
    s."SupplierId" AS "Id",
    s."Naziv" AS "Naziv",
    s."Adresa" AS "Adresa",
    s."Telefon" AS "Telefon",
    s."Napomena" AS "Napomena",
    s."UpdatedAt" AS "UpdatedAt",
    s."DataOrigin" AS "DataOrigin"
FROM latest_suppliers s;

CREATE OR REPLACE VIEW prodaja_zaglavlje AS
SELECT
    sf."SaleId" AS id,
    sf."BrojRacuna" AS broj_racuna,
    sf."SaleTimestampUtc" AS datum_prodaje,
    sf."PaymentType" AS nacin_placanja,
    sf."StoreId" AS id_objekat,
    sf."DataOrigin" AS data_origin
FROM "SalesFacts" sf;

CREATE OR REPLACE VIEW prodaja_stavke AS
SELECT
    slf."Id" AS id,
    slf."SaleId" AS id_prodaja,
    slf."ProductId" AS id_artikal,
    slf."Qty" AS kolicina,
    slf."UnitPrice" AS cena,
    slf."NabavnaCena" AS nabavna_cena,
    slf."DataOrigin" AS data_origin
FROM "SalesLineFacts" slf;

CREATE OR REPLACE VIEW "DnevnikPromena" AS
SELECT
    imf."Id"::integer AS "Id",
    imf."TipPromene" AS "TipPromene",
    imf."Datum" AS "Datum",
    imf."Iznos" AS "Iznos",
    imf."BrojDokumenta" AS "BrojRacuna",
    imf."DobavljacId" AS "DobavljacId",
    imf."ArtikalId" AS "ArtikalId",
    imf."StaraProdajnaCena" AS "StaraProdajnaCena",
    imf."NovaProdajnaCena" AS "NovaProdajnaCena",
    imf."Kolicina" AS "Kolicina",
    imf."StoreId" AS "IDObjekat",
    NULL::integer AS "RedniBroj",
    NULL::text AS "Komentar",
    imf."KorisnikIme" AS "KorisnikIme",
    imf."DataOrigin" AS "DataOrigin"
FROM "InventoryMovementFacts" imf;

-- Materialized view za povracaj_zaglavlje
DROP MATERIALIZED VIEW IF EXISTS povracaj_zaglavlje_mv;

CREATE MATERIALIZED VIEW povracaj_zaglavlje_mv AS
SELECT
    rf."ReturnId" AS id,
    COALESCE(MAX(rf."BrojZapisnika"), rf."ReturnId"::text) AS broj_zapisnika,
    MIN(rf."ReturnTimestampUtc") AS datum_povracaja,
    rf."SupplierId" AS id_dobavljac,
    MAX(rf."HeaderReason") AS razlog_povracaja,
    MAX(rf."Status") AS status,
    SUM(rf."LineAmount")::numeric(18,2) AS ukupan_iznos,
    MAX(rf."DataOrigin") AS data_origin
FROM "ReturnFacts" rf
GROUP BY rf."ReturnId", rf."SupplierId";

CREATE OR REPLACE VIEW povracaj_stavke AS
SELECT
    rf."SourceLineId" AS id,
    rf."ReturnId" AS id_povracaj,
    rf."ProductId" AS id_artikal,
    rf."Qty" AS kolicina,
    rf."UnitCost" AS cena,
    rf."LineReason" AS razlog,
    rf."ItemCondition" AS stanje_artikla,
    rf."DataOrigin" AS data_origin
FROM "ReturnFacts" rf;

CREATE OR REPLACE VIEW price_history AS
SELECT
    imf."SourceId" AS id,
    imf."ArtikalId" AS article_id,
    imf."Datum"::date AS event_date,
    imf."StaraProdajnaCena" AS old_price,
    imf."NovaProdajnaCena" AS new_price
FROM "InventoryMovementFacts" imf
WHERE imf."TipPromene" IN ('Nivelacija', 'Nivelacija cena')
  AND imf."ArtikalId" IS NOT NULL;

COMMENT ON TABLE "ReturnFacts" IS
'Analytics-side supplier return facts. Used to compute supplier quality and return-rate penalties without querying operational povracaj tables.';

COMMENT ON VIEW "Artikli" IS
'Compatibility view over ProductsDim used by migrated supplier/nivelacija analytics SQL.';

COMMENT ON VIEW "DnevnikPromena" IS
'Compatibility view over InventoryMovementFacts used by migrated supplier/nivelacija analytics SQL.';
